# Type of output
TypeOutput = Matlab BINARY

# SismoGrille = x0 y0 z0  xmin  xmax  ymin ymax  zmin zmax  
SismoGrille = 0.0 0.0 0.0 -1.5 1.5 -1.5 1.5 -1.5 1.5 100 100 100

# YES to compute the total field, NO for the diffracted field
TotalField = NO

# TypeCondition = DIRICHLET, NEUMANN or IMPEDANCE beta
TypeCondition = IMPEDANCE 2.0

# For each layer, you have to provide the coefficients rho and mu
# Rho = rho_0 rho_1 rho_2 ... rho_n
Rho = 2.0 0.6 1.0
# Mu = mu_0 mu_1 mu_2 ... mu_n
Mu = 3.0 1.5 1.0

# YES to set an absorbing condition of order 1 on the extern boundary
# NO if the exact solution (in an infinite medium) is required
FirstOrder_ABC = NO

# TypeData = NEAR_FIELD for u, SURFACE_FIELD for du/dr
TypeData = NEAR_FIELD

# NumberModes = AUTO or NumberModes = nb_modes
NumberModes = 27

# RadiusSphere = r0 r1 r2 .. r_{n+1}
# the solution is computed for r < r_{n+1}
# the impedance condition is set on r = r0
# the other radii denote an interface between two layers
RadiusSphere = 0.8 1.1 1.3 1.5

# Frequency = f
Frequency = 1.0

# OutputFile = file_name
OutputFile = SolExacteHelmMultiLayer.dat

# data for non-regression information
TypeElement = ANALYTIC
TypeEquation = HELMHOLTZ
DataNonRegressionTest = solution_helm.x 0 1
