#!/usr/bin/env python

import os, sys, network

nb_args = len(sys.argv) - 1

is_list = 0

if nb_args != 1:
    print "Usage: \"" + sys.argv[0] + " [program name]\"."
    sys.exit(0)

prog = sys.argv[1]

# Network
net = network.Network("all")

for machine in net.hosts:
    print machine.name
    (s, out) = net.LaunchFG("top -b -n 1 | grep -v cherche | grep " + prog, machine)
    print out

