# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = HARMONIC_ELASTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

FileMesh = Bicouche2D.mesh

# order of space approximation 
OrderDiscretization = 8

# boundary condition for edges of reference 3
ConditionReference = 1 DIRICHLET

# several choices for selecting properties of a media 
# MateriauDielec = ref ISOTROPE rho lambda mu
# MateriauDielec = ref YOUNG_POISSON rho E nu
# MateriauDielec = ref ORTHOTROPE rho c0000 c0011 c1111 c0101
# MateriauDielec = ref ORTHOTROPE_POISSON rho Ex Ey nu_xy Gxy
# MateriauDielec = ref ORTHOTROPE_POISSON rho Ex Ey nu_xy Gxy ANGLE theta
# MateriauDielec = ref ANISOTROPE rho c0000 c0011 c0001 c1111 c1101 c0101
MateriauDielec = 1 ISOTROPE 1.0 16.0 2.0
MateriauDielec = 2 ISOTROPE 1.0 4.0 2.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 5.0 2.0

# source on u_x
Polarization = 1.0 0.0

# PML layers are added to the domain
# AUTO means that number of layers is computed according to the space step
AddPML = YES PML_XY 4.0 AUTO

DampingPML = 2.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = -14 14 -14 14 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracBicouche2D totalBicouche2D

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = harmonic_elas2D.x 0 8
