# type of finite element
TypeElement = QUADRANGLE_LOBATTO

# type of equation
TypeEquation = HARMONIC_ELASTIC

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 2.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = DisqueElas.mesh

# order of space approximation 
OrderDiscretization = 8

# curved element
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE

# boundary condition
ConditionReference = 3 ABSORBING

# to specify transmission conditions for elastodynamics :
# ReferenceTransmission = ref PARAM rho lambda mu Decalage delta sigma
ReferenceTransmission = 4 PARAM 2.0 4.0 3.0 0.5 0.01 0

# OmegaMinusPlus = ref_minus ref_plus
OmegaMinusPlus = 2 1

# Put YES in order to treat curved interfaces
CurvilinearTransmission = YES

# MateriauDielec = ref ISOTROPE rho lambda mu sigma
MateriauDielec = 1 ISOTROPE 1.0 1.0 1.0  0.5
MateriauDielec = 2 ISOTROPE 2.5 3.0 1.5  0.2

# Gaussian source
TypeSource = SRC_VOLUME GAUSSIAN 0 1.5 0.4

# polarization of the source
Polarization = 1.0 0.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracTestGhost totalTransmissionDisqueElas

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = harmonic_elas2D.x 0 8
