# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = HARMONIC_ELASTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 2.0 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# exemple with a disk
FileMesh = DisqueSeul_QUAD.mesh REFINED 2

TypeMesh = QUAD

# order of space approximation 
OrderDiscretization = 6

TypeCurve = 1 CIRCLE

# boundary condition for edges of reference 3
ConditionReference = 1 NEUMANN

# You can provide an orthotropic material with an angle different from 0
# MateriauDielec = ref ORTHOTROPE_POISSON rho Ex Ey nu_xy G ANGLE theta
MateriauDielec = 1 ORTHOTROPE_POISSON (2.5,0.6) 10.0 2.0 0.3 2.5 ANGLE 45

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 0.5

# oriented source
Polarization = 0.707106 0.707106

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracDisqueElas totalDisqueElas

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = harmonic_elas2D.x 0 8
