# type of finite element
TypeElement = TETRAHEDRON_HIERARCHIC
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
#PhysicalFrequency = 1.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 90.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = ellipsoideVol.meshb

# order of space approximation 
OrderDiscretization = MEAN_EDGE AUTO 1.5

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 2 ABSORBING

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# snapshots on a 2-D regular grid 200x200
SismoGrille = 0 0 0 AUTO 100 100 100
# files where the diffracted and total field will be stored
FileOutputGrille = diffracEllipsoide totalEllipsoide

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz3D.x 0 8
