# type of finite element
TypeElement = HEXAHEDRON_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0 0

# file where the mesh is stored
FileMesh = tuyau.exo

# order of space approximation 
OrderDiscretization = 2

# boundary conditions (Neumann for lateral boundaries, absorbing at right, dirichlet at left)
ConditionReference = 2 NEUMANN
ConditionReference = 1 DIRICHLET
ConditionReference = 3 ABSORBING

# SRC_MODE ref numero_mode amplitude
# ref is the reference mesh where the mode should be imposed
# 0 is the number of the mode
# 1.0 is the amplitude of the mode
TypeSource = SRC_SURFACE 1 UNIFORM Polarization 1.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = DIRECT

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 100x100x100
SismoGrille = 0 0 0 AUTO 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTuyau totalTuyau

# output on meshes
SismoMeshVolumetric = AUTO
FileOutputMeshVolumetric = diffrac_TuyauMesh.bb total_TuyauMesh.bb

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz3D.x 0 8
