TypeElement = EDGE_LOBATTO

# boundary conditions on the two extremities
BoundaryCondition = DIRICHLET DIRICHLET

# order of approximation
OrderDiscretization = 4

# indices rho, mu sigma
MateriauDielec = 1  1.0 1.0 0.0

# FileMesh = REGULAR n a b
FileMesh = REGULAR 31 0.0 1.0

# choices are PiecewiseLinear, CubicSpline or Polynomial
#ApproximationC = CubicSpline 20
#ApproximationC = PiecewiseLinear 20
#ApproximationC = Polynomial 10 0 Discontinuous
ApproximationC = BSpline 24 12

#RegularizationMethod = LevMarquardtGenuine
RegularizationMethod = NewtonCG
