TypeElement = QUADRANGLE_LOBATTO
TypeEquation = TIME_ELASTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  ref_media  ref1 ref2 ref3 ref4
# nb_x : number of subdivisions along x
# ref_media reference of the elements (quadrilaterals or triangles)
# ref1, ref2, ref3, ref4 references of the edges y = ymin, x = xmax, y = ymax and x = xmin
FileMesh = Bicouche2D.mesh

# order of space approximation
OrderDiscretization = 7

# boundary condition for edges of reference 3
ConditionReference = 1 DIRICHLET

# several choices for selecting properties of a media 
# MateriauDielec = ref ISOTROPE rho lambda mu
# MateriauDielec = ref YOUNG_POISSON rho E nu
# MateriauDielec = ref ORTHOTROPE rho c0000 c0011 c1111 c0101
# MateriauDielec = ref ORTHOTROPE_POISSON rho Ex Ey nu_xy Gxy
# MateriauDielec = ref ORTHOTROPE_POISSON rho Ex Ey nu_xy Gxy ANGLE theta
# MateriauDielec = ref ANISOTROPE rho c0000 c0011 c0001 c1111 c1101 c0101
MateriauDielec = 1 ISOTROPE 1.0 16.0 2.0
MateriauDielec = 2 ISOTROPE 1.0 4.0 2.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 5.0 2.0

Polarization = 1.0 0.0

AddPML = YES PML_XY 2.0 AUTO
DampingPML = 2.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputPlane = 0.0 1000.0 3.0
# snapshots on all the mesh
SismoPlane = -12 12 -12 12 201 201
# diffracted and total field (in this test case, we compute only total field)
FileOutputPlane = diffracTest.dat totalTimeBicouche2D.dat

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 40.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_Bicouche2D.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint.dat
SismoPoint = 0.5 0.0
SismoPoint = 2.5 0.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the solution U (not the gradient)
ElectricOrMagnetic = -1

# steo time deltat
TimeStep = 0.005

# initial time of the experience, final time
TimeInterval = 0.0 20.0

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 LEAP_FROG_PML
#OrderTimeScheme = 4 RUNGE_KUTTA

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = elas2D.x 4 8
