# type of finite element
TypeElement = TRIANGLE_CLASSICAL

# type of equation
TypeEquation = HARMONIC_GALBRUN_MODEL_DIV

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 180.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = REGULAR_ANISO 17 33 0.0 4.0   -4.0 4.0   1   1 2 3 4

# order of space approximation 
OrderDiscretization = 8

# PML are added for y < ymin and y > ymax
AddPML = YES PML_Y 1.0 AUTO
DampingPML = 2.0

# refinement around a point
RefinementVertex = 2.0 0 3 2.0

# simplified Galbrun's equations
EnergyConservingAeroacousticModel = Galbrun

# Penalty coefficients
PenalizationDG = -1.0 -1.0

# number of axisymmetric modes
NumberModes = 2

# boundary conditions
ConditionReference = 2 4 DIRICHLET
ConditionReference = 1 3 PERIODICITY

# MateriauDielec = ref ISOTROPE mr mphi mz sigma rho0 c0 p0
MateriauDielec = 1 ISOTROPE 0.0 0.0 0.25 0.5 2.5 1.2 2.0

# Dirac 
TypeSource = SRC_DIRAC
Polarization = 1.0 0.0 0.0 0.0

# origin of the Dirac
OriginePhase = 2.0 0.0 0.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# snapshots on a 2-D regular grid 200x200
SismoPlaneAxi = -2.0 0.2 -4.0  4.0 0.2 -4.0   -2.0 0.2 4.0  200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlaneAxi = diffracTestGhost totalGalbrunDiracAxi

# we want to know the solution U only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = galbrun_axi.x 0 8
