# type of finite element
TypeElement = HEXAHEDRON_LOBATTO
# type of equation
TypeEquation = ACOUSTIC
# directory where the meshes are read
MeshPath = MAILLAGES/
# Frequency = a b
# will mean that omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle
IncidentAngle = 0 0

# file where the mesh is
FileMesh = cube_direct.mesh

# order of space approximation 
OrderDiscretization = 5

# boundary conditions
ConditionReference = 3 NEUMANN

# Gaussian source
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 0.0 1.0

# TimeReversal = DIRECT tmin tmax dt mesh_file output_file ref
# For a direct computation the values v.n on quadrature points of faces of reference ref are
# stored in the file output_file. The field mesh_file is currently not used 
TimeReversal = DIRECT 0.0 10.0 0.01 guide_direct_boundary.mesh cube_vn.dat 1

# Put YES to add PML layers, PML_X to add the PML along x, 
AddPML = YES PML_XYZ 1.0 AUTO

# Damping factor
DampingPML = 2.0

# automatic resolution of linear system
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# ParametersOuputGrille = t0 tf dt
ParametersOutputGrille = 0.0 11.0 1.0
# snapshots on three planes (x=0, y=0, z=0) with 200x200 on each plane
SismoGrille = 0 0 0 AUTO 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTimeRandom totalTimeCubeDirect

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# source in time
TemporalSource = RICKER

# Time step dt
TimeStep = 0.01

# TimeInterval = t0 tf
TimeInterval = 0.0 11.0

# Time-scheme used
OrderTimeScheme = 2 LEAP_FROG_PML

# we want to know the solution U
ElectricOrMagnetic = 0

# To have more informations, increase this number (0 essential informations)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 4 1







