# type of finite element
TypeElement = HEXAHEDRON_LOBATTO
# type of equation
TypeEquation = ACOUSTIC
# directory where the meshes are read
MeshPath = MAILLAGES/
# Frequency = a b
# will mean that omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle
IncidentAngle = 0 0

# file where the mesh is
FileMesh = cube_reverse.mesh

# order of space approximation 
OrderDiscretization = 5

# boundary conditions
ConditionReference = 1 NEUMANN

# Gaussian source (not exploited here)
TypeSource = SRC_VOLUME GAUSSIAN -10.0 0.0 0.0 1.0

# TimeReversal = INVERSE tmin tmax dt mesh_file output_file ref
# For a reverse computation, the source is replaced by an inhomogeneous Neumann condition
# du/dn = g(tmax - t) where the values of g on quadrature points of faces of reference ref 
# are stored in the file output_file. This file is assumed to have been generated
# by a direct simulation 
TimeReversal = INVERSE 0.0 10.0 0.01 guide_direct_boundary.mesh cube_vn.dat 1

# automatic resolution of linear system
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# ParametersOuputGrille = t0 tf dt
ParametersOutputGrille = 0.0 11.0 2.0
# snapshots on three planes (x=0, y=0, z=0) with 200x200 on each plane
SismoGrille = 0 0 0 AUTO 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTimeRandom totalTimeCubeReverse

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# source in time
TemporalSource = RICKER

# Time step dt
TimeStep = 0.01

# TimeInterval = t0 tf
TimeInterval = 0.0 11.0

# Time-scheme used
OrderTimeScheme = 2 LEAP_FROG_PML

# we want to know the solution U
ElectricOrMagnetic = 0

# To have more informations, increase this number (0 essential informations)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 4 1







