# type of finite element
TypeElement = TETRAHEDRON_CLASSICAL
# type of equation
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0 0

# file where the mesh is stored
FileMesh = lung.meshb

# order of space approximation 
OrderDiscretization = 2

# pour eviter que montjoie stoppe parce qu'il a pas de CL sur toutes les 
# faces laterales et les conditions de sortie
Exit_IfNo_BoundaryCondition = NO

# reference de la section d'entree
ConditionReference = 1 NEUMANN

# SRC_MODE ref shift nb_modes_to_compute numero_mode amplitude
# ref is the reference mesh where the mode should be imposed
TypeSource = SRC_SURFACE 1 UNIFORM Polarization 1.0

# mass matrix is explicitely computed
ExplicitMassMatrix = YES
MassMatrixSolver = Iterative 1e-11 1000

# automatic resolution of the linear system (selection of the optimal algorithm)
#TypeResolution = COCG ILUT 1e-5 0 100000 1e-2 0.1 1 
TypeResolution = COCG JACOBI 1.0
Tolerance = 1e-10

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# output on meshes
SismoMeshSurfacic = AUTO ALL 1
FileOutputMeshSurfacic = diffrac.bb TotalLung.bb
ParametersOutputMeshSurfacic = 0.0 20.0 1.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.001

# initial time of the experience, final time
TimeInterval = 0.0 10.0

# fourth order leap frog scheme on system of order 1
OrderTimeScheme = 2 THETA_SCHEME

# temporal dependance of the source
TemporalSource = RICKER

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 8 144
