# Gauss-Lobatto finite elements on hexahedrals (and classical elements for other elements)
TypeElement = HEXAHEDRON_LOBATTO

# acoustic equation to be solved (hdg formulation)
TypeEquation = ACOUSTIC_HDG

# path where the meshes are stored
MeshPath = MAILLAGES/

# direction of plane wave
IncidentAngle = 90.0 0

# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 10.0 0.0

# file where the mesh is stored
FileMesh = sphereVol.mesh

ReferenceInfinity = 1

# order of space approximation
OrderDiscretization = 4

# curved boundaries
#TypeCurve = 2 SPHERE 0.0 0.0 0.0 0.35
TypeCurve = 3 SPHERE 0.0 0.0 0.0 0.5
#TypeCurve = 1 CYLINDER 0 0 0 1.0 0.0 0.0 0.030504509961680356

# boundary conditions
ConditionReference = 1 2 3 NEUMANN
ConditionReference = 4 5 6 7 8 9 ABSORBING

# plane wave source
TypeSource = SRC_DIFFRACTED_FIELD AUTO

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 10.0 0.25
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 201 201 201
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracSphereResonant.dat totalSphereResonant.dat

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U only
ElectricOrMagnetic = 0

# time step
TimeStep = 0.00025

# initial time of the experience, final time
TimeInterval = 0.0 10.0

# time scheme
OrderTimeScheme = 4 LINEAR_RUNGE_KUTTA 2
#OrderTimeScheme = 4 LINEAR_SDIRK 1

# implicit scheme, we need to solve a linear system a each time step
# resolution of the linear system with direct method
StaticCondensation = YES Store
TypeSolver = DIRECT

# temporal dependance of the source
TemporalSource = SINUS_GAUSSIAN 16.0

# pour afficher les temps de calcul
DisplayRate = 10 YES

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = acous3D.x 4 8
