TypeElement = HEXAHEDRON_LOBATTO
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 10000.0 0.0

# FileMesh = EXTRUDE nb_layers z0 z1 ... zn nom_fichier AUTO \
#             nb_ref_surf ref0 ref1 ref2 ... ref2n
#             nb_ref_vol ref0 ref1 ref2 ... refn
FileMesh = EXTRUDE 4 0.0 0.1 0.14 0.5 0.7 piano_quad.mesh 4 2 15 8 \
           5 4 0 0 0 0 0 5 5 5 5 4 6 0 6 0 0 0 10 0 10 4 6 7 6 7 \
             0 8 0 8 0 4 0 0 0 0 9 9 9 9 9 \
           3 1 1 1   1 0 0  1 0 1   1 1 1 

# order of space approximation
OrderDiscretization = 6

# boundary condition for edges of reference 3
ConditionReference = 1 2 3 4 9 NEUMANN
ConditionReference = 5 6 7 8 10 NEUMANN

PresencePML = YES
DampingPML = 2.0
AddPML = YES XYZ 0.05 2

MateriauDielec = 1 ISOTROPE VELOCITY 340.0 1.0 0.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 z0 radius
# where (x0, y0z z0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN -0.125 0.8 0.35  0.1

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 0.01 0.001
# snapshots on all the mesh
SismoGrille = -0.32 0.9 0.4 AUTO 200 200 200
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalPianoRef.dat

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# sortie sur des maillages surfaciques
SismoMeshSurfacic = AUTO REFERENCE 5 6 7 8 10
FileOutputMeshSurfacic = diffrac_surfPiano.bb total_surfPiano.bb
ParametersOutputMeshSurfacic = 0.0 0.01 0.001

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the solution U (not the gradient)
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 1e-6

# initial time of the experience, final time
TimeInterval = 0.0 0.011

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 LEAP_FROG_PML

# temporal dependance of the source
TemporalSource = SINUS_GAUSSIAN 1e7

StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 10 144
