# Gauss-Lobatto hexahedrals
TypeElement = HEXAHEDRON_LOBATTO
# acoustic equation to be solved
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# file where the ;esh is stored
FileMesh = tuyau.exo

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = 4

# boundary conditions (Neumann for lateral boundaries, absorbing at right, neumann at left)
ConditionReference = 2 NEUMANN
ConditionReference = 1 NEUMANN
ConditionReference = 3 ABSORBING

# SRC_MODE ref numero_mode amplitude
# ref is the reference mesh where the mode should be imposed
# 0 is the number of the mode
# 1.0 is the amplitude of the mode
TypeSource = SRC_SURFACE 1 UNIFORM Polarization 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 10.0 2.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 100 100 100
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalTimeTuyau.dat

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
SismoMeshVolumetric = AUTO
# files where the snapshots on subdivided mesh are stored
FileOutputMeshVolumetric = diffrac_medit.bb total_TimeTuyauMesh.bb
# tbegin tend deltat 
ParametersOutputMeshVolumetric = 0.0 20.0 1.0

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 10.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_Tuyau.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint_Neu.dat
SismoPoint = 0.0 0.0 0
SismoPoint = 2.5 -2.5 0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.001

# initial time of the experience, final time
TimeInterval = 0.0 10.1

# fourth order leap frog scheme on system of order 1
OrderTimeScheme = 4 LEAP_FROG_PML

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 8 8
