# Gauss-Lobatto finite elements on hexahedrals
TypeElement = HEXAHEDRON_LOBATTO
# acoustic equation to be solved
TypeEquation = ACOUSTIC_DG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 0.007 0.0

# file where the mesh is stored
FileMesh = fente3D_all.mesh

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = MEAN_EDGE AUTO 1.0

MateriauDielec = 1 ISOTROPE 20.0 0.001 0

AddPML = YES PML_XYZ 1.0 AUTO
DampingPML = 2.0

# boundary condition for edges of reference 3
ConditionReference = 1 NEUMANN
ConditionReference = 2 3 NEUMANN

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 z0 radius
# where (x0, y0, z0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN -1.0 0 0 1

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 3000.0 400.0
# snapshots on all the mesh
SismoGrille = 0.1 0.1 0.1 AUTO 101 101 101
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalTimeFenteDg3D.dat

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.25

# initial time of the experience, final time
TimeInterval = 0.0 3000.0

# theta scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 LEAP_FROG_PML

# implicit scheme, we need to solve a linear system a each time step
# resolution of the linear system with direct method
TypeSolver = DIRECT

# temporal dependance of the source
TemporalSource = HARMONIC 4000.0

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 6 8
