# Gauss-Lobatto hexahedra
TypeElement = HEXAHEDRON_LOBATTO
# acoustic equation to be solved
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# file where the mesh is stored
# for a dielectric sphere, FileMesh = BALL a b 1/h ref 
FileMesh = BALL 1 2 1 1 REGULAR

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = 5

# curved element
TypeCurve = 1 SPHERE
TypeCurve = 3 SPHERE

# boundary condition for edges of reference 3
ConditionReference = 3 ABSORBING

# dielectric properties (rho, mu and sigma)
MateriauDielec = 1 ISOTROPE 0.8 1.2 0.0
MateriauDielec = 2 ISOTROPE 4.0 2.0 0.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 1.5 0.0 0.0 0.8 

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 20.0 4.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 100 100 100
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalTimeSphereDielec.dat

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
# only surfacic mesh (referenced triangles and quadrangles)
SismoMeshSurfacic = AUTO REFERENCE 1
# files where the snapshots on subdivided mesh are stored
FileOutputMeshSurfacic = diffrac_surfDielec.bb total_surfTimeDielec.bb
ParametersOutputMeshSurfacic = 0.0 20.0 4.0

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 20.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_SphereDie.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint.dat
SismoPoint = 0.5 0.0 0
SismoPoint = 1.5 0.0 0
SismoPoint = 0.5 1.0 0.2

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U only
ElectricOrMagnetic = -2

# steo time deltat
TimeStep = 0.02

# initial time of the experience, final time
TimeInterval = 0.0 20.0

# leap-frog scheme or order four (technique of modified equation)
# applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 4 LEAP_FROG

# temporal dependance of the source
TemporalSource = SINUS_GAUSSIAN 0.1

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 4 8
