# type of finite element
TypeElement = TETRAHEDRON_DG_LOBATTO
# type of equation
TypeEquation = ACOUSTIC_DG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 100.0 0.0
#PhysicalFrequency = 1.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 90.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = ellipsoideVol.meshb

# order of space approximation 
OrderDiscretization = MEAN_EDGE AUTO 1.5

MateriauDielec = 1 ISOTROPE 0.002 20.0 0.0

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 2 ABSORBING

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_VOLUME GAUSSIAN 0.0 -8.5 0.0 0.5

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

ParametersOutputGrille = 0.0 0.21 0.04
# snapshots on a 2-D regular grid 200x200
SismoGrille = 0 0 0 AUTO 200 500 200
# files where the diffracted and total field will be stored
FileOutputGrille = diffracEllipsoide totalEllipsoide

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

TemporalSource = SINUS_GAUSSIAN 1000.0
TimeStep = 5e-6
TimeInterval = 0.0 0.21

OrderTimeScheme = 3 ADAMS_BASHFORTH

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 5 72
