TypeElement = HEXAHEDRON_LOBATTO
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = ./
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  zmin zmax ref_media  ref1 ref2 ref3 ref4 ref5 ref6
# nb_x : number of subdivisions along x
# ref_media reference of the elements (hexahedrals or tetrahedrals)
# ref1, ref2, ref3, ref4, ref5, ref6 references of the faces x = xmin, y = ymin, z = zmin, z = zmax, y = ymax and x = xmax
FileMesh = REGULAR 8 -2.0  2.0  -2.0  2.0  -2 2 1  3  3  3  3  3  3

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = 3

# boundary condition for edges of reference 3
ConditionReference = 3 NEUMANN

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 z0 radius
# where (x0, y0z z0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 0.0  1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 10.0 2.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 100 100 100
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalCubeTime.dat

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 10.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalCubePoint.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint.dat
SismoPoint = 0.5 0 0
SismoPoint = -1.5 0.5 0

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
SismoMeshVolumetric = AUTO
# files where the snapshots on subdivided mesh are stored
FileOutputMeshVolumetric = diffrac_meditCube.bb total_meditCube.bb
# tbegin tend deltat 
ParametersOutputMeshVolumetric = 0.0 10.0 2.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the solution U (not the gradient)
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.015

# initial time of the experience, final time
TimeInterval = -1.0 10.0

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 LEAP_FROG

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous3D.x 4 8
