# Gauss-Lobatto finite elements on hexahedrals (and classical elements for other elements)
TypeElement = HEXAHEDRON_LOBATTO

# acoustic equation to be solved (hdg formulation)
TypeEquation = ACOUSTIC

# path where the meshes are stored
MeshPath = ./

# direction of plane wave
IncidentAngle = 90.0 0

# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 2.1e6 0.0

# file where the mesh is stored
FileMesh = finalSphere.mesh

ReferenceInfinity = 1

# order of space approximation
OrderDiscretization = 10

# curved boundaries
TypeCurve = 1 SPHERE
TypeCurve = 4 SPHERE

# boundary conditions
ConditionReference = 2 3 NEUMANN
ConditionReference = 1 ABSORBING

MateriauDielec = 1 ISOTROPE RADIAL example/helm_radial/rho.don 0.0 1.0 \
                            RADIAL example/helm_radial/mu.don 0.0 1.0 \
                            RADIAL example/helm_radial/sigma.don 0.0 1.0

# plane wave source
TypeSource = SRC_VOLUME GAUSSIAN 0 0 0.9847880883810000 0.015 0.02

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 1.0e-4 5.0e-7
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 201 201 201
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracSphere.dat totalSphere.dat

# non-linear solver used to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U only
ElectricOrMagnetic = 0

RandomInitialCondition = Small

# time step
TimeStep = 2e-9
#TimeStep = AUTO 1.0e-7

# initial time of the experience, final time
TimeInterval = 0.0 1.0e-4

# time scheme
#OrderTimeScheme = 4 RUNGE_KUTTA
OrderTimeScheme = 4 LEAP_FROG

# temporal dependance of the source
TemporalSource = SINUS_GAUSSIAN 2.0e12

# pour afficher les temps de calcul
DisplayRate = 10 YES

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = acous3D.x 4 8
