# TypeOutput = Medit ASCII
TypeOutput = Matlab BINARY

# SismoPlane = xmin xmax ymin ymax 200 200
SismoPlane = -5.0 5.0 -5.0 5.0 200 200

# SismoCircle = x0 y0 r n
#SismoCircle = 0 0 2.0 400

# TotalField = NO to compute the diffracted field
TotalField = YES

# TypeCondition = NEUMANN or DIRICHLET or IMPEDANCE beta
TypeCondition = DIRICHLET

# rho = mu = 1, the velocity is not placed here
Rho = 1.0 
Mu = 1.0

# FirstOrder_ABC = YES for a first-order absorbing boundary condition
FirstOrder_ABC = CURVED 1 GRAZING

# TypeData = NEAR_FIELD to get the solution u
TypeData = NEAR_FIELD

# NumberModes = AUTO for an automatic computation of the number of Bessel functions
NumberModes = AUTO

# RadiusCircle = r0 r1
# The solution is computed between r0 and r1
RadiusCircle = 2.0 5.0

# Frequency = freq (used only in time-harmonic computation)
Frequency = 1.0

# MeshFile = file_name (used only for Medit ouputs)
MeshFile = circle.mesh

# OutputFile = name.dat
OutputFile = Un.dat

