# intervalle de temps de la simulation
TimeInterval = 0 0.1 
TimeStep = 1e-6     

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)            
DisplayFrequency = 1e-4                                                                          
  
# parametres physiques de la corde                                                               
# String = L A rho T0 E I G k_prime amo(0) amo(1) Nx is_sruck K_hammer R_hammer                  
String = 1.05 9.7993e-7 7850 880  2.02e+11 7.6416e-14 7.77e10 0.85 7.69e-3 5.5e-2 1.0 40 1 4.3e+06 0 
String = 1.05 9.7993e-7 7850 884  2.02e+11 7.6416e-14 7.77e10 0.85 7.69e-3 5.5e-2 1.0 40 1 4.3e+06 0 

# excitation par une force donnee dans un fichier                                  
Hammer = FORCE EXPERIMENT example/multi_string/ForceExt48kH.dat  0.127 0.02 2011 2.0833e-05 

# parametres pour la condition d impedance
Bridge = 2 2
Impedance = example/PIANO/BRIDGE/Masses_C2.txt example/PIANO/BRIDGE/Raideurs_C2.txt  example/PIANO/BRIDGE/Resist_C2.txt

# parametres de discretisation en temps                                                          
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25                                               
StringPermutations = PERMUT_ALL      

# donnees initiales sur la corde                                                                 
StringInitialData = NONE                                                                         

# interpolation sur une grille reguliere                                                         
StringInterp = 30                                                                                
StringInterpTimeGrid = 0 0.35 2.5e-4                                                             
                                                                                                 
# sismogramme d'un point de la corde
StringSismo = 0.06                                                                               
StringSismoTimeGrid = 0  1 5e-5     

DirectoryOutputString = ./

FileOutputString = SismoLM_MultiImpedanceLin.txt SismoHammerMultiImpedanceLin.txt ForceMarteauMultiImpedanceLin.txt EnergyNoteMultiImpedanceLin.txt
FileOutputSismoString = SismoStringMultiImpedanceLin_ SismoLastPointMultiImpedanceLin_ SismoCrushMultiImpedanceLin_ ValMultiImpedanceLin_

# sortie d'un fichier avec l'energie                                                             
Energy = 0 1.0 1e-4

# parametre de convergence de la methode de Newton                                               
NewtonParam = 1e-12 20 1e-9

DataNonRegressionTest = StringImpedanceStiffLIN.x 0 1
