TypeElement = HEXAHEDRON_LOBATTO
TypeEquation = ACOUSTIC

# intervalle de temps de la simulation
TimeInterval = 0 0.003 # court
TimeStep = 5.0e-7
#pour 100 points

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)
DisplayFrequency = 1e-3

# Plan de cordes utilise
# PlanCordes = AUTO  

# parametres physiques de la corde E3 GH05 (2 cordes)
# String = L A rho T0 E I G kprime PHI_DAMPING Ru Rv Rphi Etau Etav Etaphi Nx is_struck 
# StringDamping = FALSE
String = 0.899 2.12e-7  7850 143.0 2.0e11 3.59e-15 8.0e10 0.85 PHI_DAMPING 2.5e-1 5.0e-1 2.5e-1 3.0e-9 1.0e-9 3.0e-9 1.0 80 1
String = 0.899 2.12e-7  7850 143.4 2.0e11 3.59e-15 8.0e10 0.85 PHI_DAMPING 2.5e-1 5.0e-1 2.5e-1	3.0e-9 1.0e-9 3.0e-9 1.0 80 1

# parametres du marteau
# HammerDamping = FALSE
Hammer = FORCE EXPERIMENT DATA/FhrecE3f.txt 0.090 0.01 2011 1.953125e-5

# fonction de repartition sur la table : x0 y0 r0 amplitude
MecanicPolarization = 0 0 1
MecanicInitialCondition = USER 0.35 0.636 0.1 1

# parametres de discretisation en temps
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25
StringPermutations = PERMUT_ALL

# donnees initiales sur la corde
StringInitialData = NONE

# sismogramme d un point de la corde
StringSismo = 0.010 0.010
StringSismoTimeGrid = 0 0.003 1.953125e-5   

# sortie d un fichier avec l energie
Energy = 0 0.003 1.953125e-5

# parametre de convergence de la methode de Newton
NewtonParam = 1e-12 20 1e-9

# angle au chevalet
Bridge = 4 4  

# amortissement au chevalet
ModalDamping = 2e-4 0.07 0
# ModalDamping = 0 0 0

# pour le maillage
MeshPath = MAILLAGES/
AcousticFileMesh = EXTRUDE 4 -0.3 -0.2  0 0.2 0.3 GH05-SB_boxV4.msh AUTO \
7  \
0 0 0 0 0 0 8    14 14 14 9 0 14 14 \
10 0 10 9 0 0 8  11 12 13 0 0 0 0 \
10 0 10 9 0 0 8  14 14 14 9 0 14 14 \
0 0 0 0 0 0 8    8 8 8 8 8 8 8 \
7 \
1 1 1 1 1 1 1  \
1 1 1 0 1 1 1  \
1 1 1 0 1 1 1  \
1 1 1 1 1 1 1 

# Pour les pml
AddPML = YES PML_XYZ 0.04 2
DampingPML = 2.0

# pour les materiaux
# (11) SB ; (13) RT ; (12) BR ; 
MecanicMateriauDielec = 11 ORTHOTROPE 440 12.0e9 1.1e9   0.26 0.015   0.66e9  1.2e9   42e6    0.85 0.85 ANGLE 88
MecanicMateriauDielec = 13 ORTHOTROPE 440 12.0e9 2.1e9   0.26 0.015   0.66e9  1.2e9   42e6    0.85 0.85 ANGLE -72
MecanicMateriauDielec = 12 ORTHOTROPE 730 14.0e9 2.1e9   0.31 0.093   1.61e9  1.06e9  0.46e6  0.85 0.85 ANGLE 88

# vitesse du son et densite du milieu
Velocity = 340.0
Density = 1.29

# pour les conditions aux limites
AcousticConditionReference = 1 2 3 4 5 6 7 8 9 10 11 12 13 NEUMANN

MecanicConditionReference = 1 SUPPORTED 2
MecanicConditionReference = 2 NEUMANN

# reference(s) de la table
ReferencePlate = 11 12 13 

# pour l'epaisseur
MecanicThicknessPlate = VARIABLE 11 0.005
MecanicThicknessPlate = VARIABLE 12 0.010
MecanicThicknessPlate = VARIABLE 13 0.010


# pour les elements finis
MecanicOrderDiscretization = 4
AcousticOrderDiscretization = 4

# pour forcer Montjoie a n'avoir que des hexahedres (condensation de masse)
AcousticTypeMesh = HEXA

# pour la diagonalisation 
Eigenvalue = YES SHIFTED CENTERED 20.0 40
EigenvalueTolerance = 1e-6
DirichletCoefEigenvalue = 1e12

# pour les sorties 2D sur une grille (-> matlab)
MecanicParametersOutputPlane = 0.0 3e-2 3e-5
MecanicSismoPlane = AUTO 200 200
MecanicFileOutputPlane = toto GH05Plate.dat

# pour les sorties 3D sur une grille
AcousticParametersOutputGrille = 0.0 3e-2 3e-5
AcousticSismoGrille = 0.59 1.26 0.2001 AUTO 100 100 100
AcousticFileOutputGrille = toto GH05Coupe.dat

AcousticParametersOutputPoint = 0.0 0.003  1.953125e-5
AcousticFileOutputPoint = totoE3GH05 SismoPianoE3GH05.dat
AcousticSismoPoint = 0.15 0.667 0.1
AcousticSismoPoint = 0.35 0.636 0.1

MecanicParametersOutputPoint = 0 0.003  1.953125e-5
MecanicFileOutputPoint = SismoAlterPlaqueE3GH05.dat SismoPlaqueE3GH05.dat
# sismo table 
MecanicSismoPoint = 0.15 0.667
MecanicSismoPoint = 0.35 0.636

# pour sortir le vecteur Lambda Brut de decoffrage
# MecanicSismoLambda = 0 2.0 1e-5 100
# ne sortir que les 100 premieres vp
# MecanicSismoLambdaTruncate = 100


# parametres de sortie
ElectricOrMagnetic = -2
OutputFormat = BINARY DOUBLE
NormeMaxSolution = 100.0

# ordre et type du schema en temps pour le volume
OrderTimeScheme = 2 LEAP_FROG_PML
#OrderTimeScheme = 4 LEAP_FROG

#ExplicitMatrixFEM = YES
ExplicitMatrixFEM = NO

#DisplayComputationTime = GLOBAL 100

#SaveReprise = 2000
#LoadReprise = NO

DirectoryOutputString = ./

#PathReprise = /lustre/chaigne/pianoCd5all/
# /home/chaigne/pianoCd5/
#PathReprise = /scratch/durufle/
#RegroupReprise = 8

# pour les sorties des valeurs propres 
FileEigenvalue = eigenGH05

# solvers
TypeSolver = DIRECT
NonLinearSolver = MINPACK 1e-15 50

# degre de bavardage
PrintLevel = 2

DataNonRegressionTest = PianoStiffNL.x 100 24
