# intervalle de temps de la simulation
TimeInterval = 0 1e-3                                                                                               
TimeStep = 1e-6     

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)
DisplayFrequency = 1e-4
  
# parametres physiques de la corde  
# String = L A rho T0 E I G k_prime amo(0) amo(1) Nx is_sruck K_hammer R_hammer
String = 1.05 9.7993e-7 7850 880  2.02e+11 7.6416e-14 7.77e10 0.85 7.69e-3 5.5e-2 1.0 40 1 4.3e+06 0

# excitation par une force donnee dans un fichier                                  
Hammer = FORCE EXPERIMENT example/multi_string/ForceExt48kH.dat  0.127 0.02 2011 2.0833e-05 

# parametres de discretisation en temps
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25
StringPermutations = PERMUT_ALL      

# donnees initiales sur la corde
StringInitialData = NONE

# interpolation sur une grille reguliere
#StringInterp = 30
#StringInterpTimeGrid = 0 0.35 2.5e-4

# sismogramme d'un point de la corde
StringSismo = 0.06
StringSismoTimeGrid = 0  1 5e-5     1

# sortie d'un fichier avec l'energie
Energy = 0 1.0 1e-4 1

DirectoryOutputString = ./

FileOutputString = SismoLM_Piano.txt SismoHammerPiano.txt ForceMarteauPiano.txt EnergyNotePiano.txt
FileOutputSismoString = SismoStringPiano_ SismoLastPointPiano_ SismoCrushPiano_ ValPiano_
FileOutputEnergyPiano = EnergyPianoTest.txt

# parametre de convergence de la methode de Newton
NewtonParam = 1e-12 20 1e-9

# angle au chevalet
Bridge = 2

# amortissement au chevalet
ModalDamping = 0 100 0              

# pour le maillage
MeshPath = MAILLAGES/Piano/
AcousticFileMesh = EXTRUDE 4 0 0.05 0.20 0.35 0.40  SteinwayIRCAM.msh 2 5 5 2 \
6 \
0 0 0 0 0 5     0 0 6 0 0 0 \
6 6 6 0 0 5     7 8 0 0 0 0 \
6 6 6 0 0 5     0 0 6 0 0 0 \
0 0 0 0 0 5     5 5 5 5 0 0 \
4 \
1 1 1 1 \
1 1 0 1 \
1 1 0 1 \
1 1 1 1


# pour les materiaux 
MecanicMateriauDielec = 8 ORTHOTROPE 380.0 11.0e9 650.0e6 0.26 0.014 0.66e9 1.2e9 42.0e6 0.85 0.85 ANGLE -40  
MecanicMateriauDielec = 7 ORTHOTROPE 620   16.3e9 11.1e8  0.26 0 11.8e8 9.2e8  1.9e8  0.85 0.85  ANGLE  54.4   
# vitesse du son et densite du milieu
Velocity = 340.0
Density = 1.29

# pour les conditions aux limites
AcousticConditionReference =  6 7 8 NEUMANN
AcousticConditionReference = 1 2 3 4 5 ABSORBING
MecanicConditionReference = 1 SUPPORTED 2

# reference(s) de la table
ReferencePlate = 7 8

# pour l'epaisseur
MecanicThicknessPlate = 0.02

# fonction de repartition sur la table : x0 y0 r0 amplitude 
MecanicPolarization = 0 0 1                            
MecanicInitialCondition = USER 0.59 1.26 0.1 400

# pour les elements finis
MecanicOrderDiscretization = 2
AcousticOrderDiscretization = 2
# pour forcer Montjoie a n'avoir que des hexahedres (condensation de masse)
AcousticTypeMesh = HEXA

# pour la diagonalisation 
Eigenvalue = YES SHIFTED CENTERED 30.0 40
EigenvalueTolerance = 1e-6
DirichletCoefEigenvalue = 1e12

# pour les sorties 2D sur une grille (-> matlab)
#MecanicParametersOutputPlane = 0.0 1e-2 3e-4 
#MecanicSismoPlane = AUTO 200 200
#MecanicFileOutputPlane = toto SteinwayPlate.dat

# pour les sorties 3D sur une grille
#AcousticParametersOutputGrille = 0.0 3e-4 1e-5
#AcousticSismoGrille = 0.59 1.26 0.2 AUTO 100 100 100
#AcousticFileOutputGrille = toto SteinwayCoupe.dat

# pour des sismos de pression
AcousticParametersOutputPoint = 0.0 2.0 1e-6
AcousticFileOutputPoint = toto SismoPianoTest.dat      
AcousticSismoPoint = 0 1.0 0.35
AcousticSismoPoint = 0 1.0 0.05
AcousticSismoPoint = 1.3 1.7 0.35

# parametres de sortie
ElectricOrMagnetic = -2
OutputFormat = BINARY DOUBLE

# ordre et type du schema en temps pour le volume
OrderTimeScheme = 2 LEAP_FROG          
                                          

# pour les sorties des valeurs propres 
FileEigenvalue = eigenvalSteinway

# solvers
TypeSolver = DIRECT
NonLinearSolver = NEWTON 1e-15 50

# degre de bavardage
PrintLevel = 3

DataNonRegressionTest = PianoStiffNL.x 0 1
