TypeEquation = TIME_REISSNER_MINDLIN
TypeElement = TRIANGLE_LOBATTO

# pour le maillage
MeshPath = MAILLAGES/Piano/
FileMesh = soundboard2d.mesh

# pour les materiaux et conditions aux limites
# MateriauDielec = 1 2 5 6 ISOTROPE 1.0 4.0 2.0
# MateriauDielec = n CLE rho | Ex Ey | nu_xy nu_yx | G_xy G_xz G_yz | K Ky | ANGLE theta_orth 

# TOUT PAREIL
# MateriauDielec = 1 ORTHOTROPE 380 11.0e9 650e6        0.26 0.015    0.66e9  1.2e9  42e6   0.85 0.85 ANGLE -40
# MateriauDielec = 2 ORTHOTROPE 380 11.0e9 650e6        0.26 0.015    0.66e9  1.2e9  42e6   0.85 0.85 ANGLE -40
# MateriauDielec = 5 ORTHOTROPE 380 11.0e9 650e6        0.26 0.015    0.66e9  1.2e9  42e6   0.85 0.85 ANGLE -40
# MateriauDielec = 6 ORTHOTROPE 380 11.0e9 650e6        0.26 0.015    0.66e9  1.2e9  42e6   0.85 0.85 ANGLE -40

# REALISTE
MateriauDielec = 1 ORTHOTROPE 380 11.0e9 650e6        0.26 0.015    0.66e9  1.2e9  42e6    0.85 0.85 ANGLE -40
MateriauDielec = 2 ORTHOTROPE 380 11.0e9 650e6        0.26 0.015    0.66e9  1.2e9  42e6    0.85 0.85  ANGLE 54.4
MateriauDielec = 5 ORTHOTROPE 750 13.7e9 2.24e9       0.3  0        1.61e9  1.06e9 0.46e9  0.85 0.85 ANGLE -40
MateriauDielec = 6 ORTHOTROPE 750 13.7e9 2.24e9       0.3  0        1.61e9  1.06e9 0.46e9  0.85 0.85 ANGLE -40

ConditionReference = 1 2 3 4 SUPPORTED 2

# pour l'epaisseur
ThicknessPlate = VARIABLE 1 0.009
ThicknessPlate = VARIABLE 2 0.034
ThicknessPlate = VARIABLE 5 0.054
ThicknessPlate = VARIABLE 6 0.029
# ThicknessPlate = 0.02

# pour les elements finis
OrderDiscretization = 3
# pour forcer Montjoie a n'avoir que des quadrilateres (condensation de masse)
TypeMesh = QUAD

# pour la diagonalisation 
Eigenvalue = YES SHIFTED CENTERED 30.0 20
EigenvalueTolerance = 1e-6
DirichletCoefEigenvalue = 1e9

# pour les sorties des modes sur une grille (-> matlab)
SismoPlane = AUTO 200 200
FileOutputPlane = toto SortieSoundboardgrille2D

DirectoryOutputString = ./

# SismoMeshVolumetric = AUTO
# FileOutputMeshVolumetric = diff SortieSoundboard2D.bb
# ElectricOrMagnetic = -1
OutputFormat = BINARY DOUBLE

# pour les sorties des valeurs propres 
FileEigenvalue = eigenval2D

ElectricOrMagnetic = -2

# solvers
TypeSolver = DIRECT
NonLinearSolver = NEWTON 1e-15 50

# degre de bavardage
PrintLevel = 3

DataNonRegressionTest = soundboard.x 20 1
