TypeEquation = STATIC_ELASTIC
TypeElement = TETRAHEDRON_LOBATTO

# pour le maillage
MeshPath = MAILLAGES/Piano/
FileMesh = EXTRUDE 3 -0.032 -0.003 0.003 0.035 SteinwayChevaletCourtPlaque.msh 1 1 1 7 \
          0 0 0 0 1 0 0    3 0 0 0 0 3 0  \
          4 0 0 7 0 0 0    3 3 3 3 0 0 0  \
          0 0 0 0 0 0 1    0 0 0 0 6 6 0  \
          6  0 1 0 0 1 0 \
          1 1 1 1 1 1 \
          0 0 0 0 2 2

# pour les materiaux et conditions aux limites
MateriauDielec = 1 ORTHOTROPE_POISSON 440 15.9e9 0.69e9 0.39e9 0.44 0.38 0.47 0.62e9 0.77e9 0.036e9 ANGLE 90 49 
MateriauDielec = 2 ORTHOTROPE_POISSON 680 14e9 2.28e9 1.16e9 0.449 0.518 0.707 1.64e9 1.08e9 0.47e9 ANGLE 90 -41

ConditionReference = 7 DIRICHLET
ConditionReference = 1 2 3 5 6 NEUMANN
ConditionReference = 4 SUPPORTED 2

# pour les elements finis
OrderDiscretization = 2
# pour forcer Montjoie a n'avoir que des hexahedres (condensation de masse)
TypeMesh = HEXA

# pour la diagonalisation 
Eigenvalue = YES SHIFTED CENTERED 30.0 20
EigenvalueTolerance = 1e-6

# pour les sorties des modes sur une grille (-> matlab)
SismoPlane = 0 -0.07 0  1.441 -0.07 0   0 2.0 0  200 200
FileOutputPlane = toto SortieSoundboard3D
ElectricOrMagnetic = -2
OutputFormat = BINARY DOUBLE

# pour les sorties des valeurs propres 
FileEigenvalue = eigenval3D

# solvers
TypeSolver = DIRECT
NonLinearSolver = NEWTON 1e-15 50

# degre de bavardage
PrintLevel = 3

DataNonRegressionTest = static_elastic.x 20 1
