TypeEquation = TIME_REISSNER_MINDLIN

# intervalle de temps de la simulation
TimeInterval = 0 1e-2 
TimeStep = 1e-6     

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)                       
DisplayFrequency = 1e-4                                                                                     
  
# parametres physiques de la corde                                                                          
# String = L A rho T0 E I G k_prime amo(0) amo(1) Nx is_sruck K_hammer R_hammer                             
String = 1.05 9.7993e-7 7850 880  2.02e+11 7.6416e-14 7.77e10 0.85 7.69e-3 5.5e-2 1.0 40 1 4.3e+06 0            

# excitation par une force donnee dans un fichier                                  
Hammer = FORCE EXPERIMENT example/multi_string/ForceExt48kH.dat  0.127 0.02 2011 2.0833e-05 

# parametres de discretisation en temps                                                                     
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25                                                          
StringPermutations = PERMUT_ALL      

# donnees initiales sur la corde                                                                            
StringInitialData = NONE                                                                                    

# interpolation sur une grille reguliere                                                                    
StringInterp = 30                                                                                           
StringInterpTimeGrid = 0 0.35 2.5e-4                                                                        
                                                                                                            
# sismogramme d'un point de la corde
StringSismo = 0.06                                                                                          
StringSismoTimeGrid = 0  1 5e-5     

DirectoryOutputString = ./

FileOutputString = SismoLM_Soundboard.txt SismoHammerSoundboard.txt ForceMarteauSoundboard.txt EnergyNoteSoundboard.txt
FileOutputSismoString = SismoStringSoundboard_ SismoLastPointSoundboard_ SismoCrushSoundboard_ ValSoundboard_

# sortie d'un fichier avec l'energie                                                                        
Energy = 0 1.0 1e-4

# parametre de convergence de la methode de Newton                                                          
NewtonParam = 1e-12 20 1e-9

# angle au chevalet                                                                                         
Bridge = 2                                                                                                  

# amortissement au chevalet
ModalDamping = 0 100 0              

# pour le maillage
MeshPath = MAILLAGES/Piano/
FileMesh = soundboard2D.msh

# pour les materiaux et conditions aux limites
MateriauDielec = 1 ORTHOTROPE 380.0 11.0e9 650.0e6 0.26 0.014 0.66e9 1.2e9 42.0e6 0.85 0.85 ANGLE -40
MateriauDielec = 2 ORTHOTROPE 620   16.3e9 11.1e8  0.26 0 11.8e8 9.2e8  1.9e8  0.85 0.85  ANGLE  54.4
ConditionReference =  1 4 SUPPORTED 2


# pour l'epaisseur
ThicknessPlate = 0.02

# fonction de repartition sur la table : x0 y0 r0 amplitude 
Polarization = 0 0 1                                                                                        
MecanicInitialCondition = USER 0.59 1.26 0.1 400

# pour les elements finis
OrderDiscretization = 2
# pour forcer Montjoie a n'avoir que des quadrilateres (condensation de masse)
TypeMesh = QUAD

# pour la diagonalisation 
Eigenvalue = YES SHIFTED CENTERED 30.0 80
EigenvalueTolerance = 1e-6
DirichletCoefEigenvalue = 1e12 

# pour les sorties des modes sur une grille (-> matlab)
ParametersOutputPlane = 0.0 1e-2 3e-4 
SismoPlane = AUTO 200 200
FileOutputPlane = toto SortieSoundboard2DTime
ElectricOrMagnetic = -2
OutputFormat = BINARY DOUBLE

# pour les sorties des valeurs propres 
FileEigenvalue = eigenval2D

# solvers
TypeSolver = DIRECT
NonLinearSolver = NEWTON 1e-15 50

# degre de bavardage
PrintLevel = 3

DataNonRegressionTest = StringSoundboardStiffNL.x 34 1
