# type of finite element
TypeElement = QUADRANGLE_LOBATTO

# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 5.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file where the mesh is stored
FileMesh = carre_inclusion.mesh

# order of space approximation 
OrderDiscretization = 10

# AddPML = YES region_pml thickness nb_layers
AddPML = YES PML_XY- 0.3 2
DampingPML = 2.0

MixedFormulation = YES

# curves that are circle
# B4F100 indicates that all curves between 4 and 100 are circles
TypeCurve = B1F100 CIRCLE

# MateriauDielec = ref ISOTROPE rho mu
MateriauDielec = 1 ISOTROPE 1 1
MateriauDielec = 2 ISOTROPE 4.0 0.8

# boundary condition for edges of reference 3
ConditionReference = 101 102 NEUMANN

# surface source with a gaussian
TypeSource = SRC_SURFACE 102 GAUSSIAN 0.0 3.5  1.8 2.8 Polarization 1.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = DIRECT

StaticCondensation = YES Store

# non-linear solver to solve Fi(x) = y
NonLinearSolver = MINPACK 1e-15 50

# ParametersOutputPlane = t0 tf dt_display
ParametersOutputPlane = 0.0 16.0 1.0
# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 600 600
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracCarre totalPadeInclusion

# time step dt
TimeStep = 0.01
# time interval
TimeInterval = 0.0 16.1

# OrderTimeScheme = order scheme
OrderTimeScheme = 6 PADE_SCHEME

# TemporalSource = type_source parameters
TemporalSource = SINUS_GAUSSIAN 2.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous2D.x 10 8
