# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = ACOUSTIC
# directory where the meshes are read
MeshPath = MAILLAGES/
# Frequency = a b
# will mean that omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle
IncidentAngle = 0

# file where the mesh is
FileMesh = guide_reverse.mesh

# order of space approximation 
OrderDiscretization = 8

# boundary conditions
ConditionReference = 1 2 3 4 NEUMANN

# RANDOM xmin xmax ymin ymax troncX troncY offset amplitude file precision rho_infty
MateriauDielec = 2 ISOTROPE 1.0 1.0
MateriauDielec = 1 ISOTROPE RANDOM 10.0 30.0 -10 10 1.0 1.0  1  2.0 example/helm2D/rand.don FLOAT 1.0   \
                             1.0 0.0

# gaussian source (not exploited here)
TypeSource = SRC_VOLUME GAUSSIAN -10.0 0.0 1.0

# TimeReversal = INVERSE tmin tmax dt mesh_file output_file ref
# For a reverse computation, the source is replaced by an inhomogeneous Neumann condition
# du/dn = g(tmax - t) where the values of g on quadrature points of faces of reference ref 
# are stored in the file output_file. This file is assumed to have been generated
# by a direct simulation 
TimeReversal = INVERSE 0.0 200.0 0.01 guide_direct_boundary.mesh guide_direct_vn.dat 4

# Put YES to add PML layers, PML_X to add the PML along x, 
AddPML = YES PML_X- 1.0 AUTO

# Damping factor
DampingPML = 2.0

# automatic resolution of linear system
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# t0 tf dt
ParametersOutputPlane = 0.0 201.0 10.0
# snapshots on a 2-D regular grid 200x100
SismoPlane = AUTO 200 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracTimeRandom totalTimeRandomReverse

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# source in time (not exploited here)
TemporalSource = RICKER

# Time step dt
TimeStep = 0.01

# TimeInterval = t0 tf
TimeInterval = 0.0 200.1

# Time-scheme used
OrderTimeScheme = 2 LEAP_FROG_PML

# we want to know the solution U
ElectricOrMagnetic = 0

# To have more informations, increase this number (0 essential informations)
PrintLevel = 2

DataNonRegressionTest = acous2D.x 20 1







