TypeElement = QUADRANGLE_LOBATTO
#TypeElement = QUADRANGLE_DG_LOBATTO
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# file where the mesh is stored
FileMesh = ellipse_dielec.mesh

TypeMesh = QUAD

# order of space approximation
OrderDiscretization = 7

# curves
TypeCurve = 1 ELLIPSE 0.0 0.0  5.0 2.0

# boundary conditions (Neumann for lateral boundaries, absorbing at right, neumann at left)
ConditionReference = 3 DIRICHLET

MateriauDielec = 1 ISOTROPE 2.0 2.0 0.0
MateriauDielec = 2 ISOTROPE 4.0 1.0 0.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 3.0 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputPlane = 0.0 40.0 4.0
# snapshots on all the mesh
SismoPlane = AUTO 100 100
# diffracted and total field (in this test case, we compute only total field)
FileOutputPlane = diffracTest.dat totalTimeEllipseDie.dat

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 40.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_Ellipse.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint_Neu.dat
SismoPoint = 5.5 0.5
SismoPoint = -3.0 3.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.005

# initial time of the experience, final time
TimeInterval = 0.0 20.0

# leap frog scheme on system of order 1
OrderTimeScheme = 4 LEAP_FROG_PML

AddPML = YES PML_XY 1.0 AUTO
DampingPML = 2.0

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous2D.x 4 8

