# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = ACOUSTIC_DG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 100.0 0.0
#PhysicalFrequency = 1.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 90.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = ellipse_pml.mesh

# order of space approximation 
OrderDiscretization = MEAN_EDGE AUTO 0.8

MateriauDielec = 1 ISOTROPE 0.002 20.0 0.0

# curved element
TypeCurve = 1 ELLIPSE 0 0 7.957747154594768e-01 7.957747154594767

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 3 ABSORBING

# Gaussian source
TypeSource = SRC_VOLUME GAUSSIAN -1.5 -8 0.5

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

ParametersOutputPlane = 0.0 0.21 0.04
# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 200 400
# files where the diffracted and total field will be stored
FileOutputPlane = diffracEllipseHybrid totalEllipseHybrid

TemporalSource = SINUS_GAUSSIAN 1000.0
TimeStep = 1.25e-5
TimeInterval = 0.0 0.21

OrderTimeScheme = 3 ADAMS_BASHFORTH

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous2D.x 5 8
