TypeElement = QUADRANGLE_LOBATTO
#TypeElement = QUADRANGLE_DG_LOBATTO
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# file where the mesh is stored
FileMesh = fente.mesh

TypeMesh = QUAD

# order of space approximation
OrderDiscretization = 8

# boundary condition for edges of reference 3
ConditionReference = 3 ABSORBING
ConditionReference = 1 NEUMANN

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN -2.5 0.0 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputPlane = 0.0 40.0 4.0
# snapshots on all the mesh
SismoPlane = AUTO 200 401
# diffracted and total field (in this test case, we compute only total field)
FileOutputPlane = diffracTest.dat totalTimeFente.dat

# tend tbegin deltat for snasphots on line
ParametersOutputLine = 0.0 40.0 0.1
# diffracted and total field (in this test case, we compute only total field)
FileOutputLine = diffracPoint.dat totalLine_Fente.dat
# you can add as many lines as you want, all the results will be stored in the same file totalLine_Fente.dat
SismoLine = -4.5 4.5 0.0 0.0 200

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 40.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_Fente.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint.dat
SismoPoint = 2.5 0.0
SismoPoint = -2.5 0.0
SismoPoint = 0.0 0.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.01

# initial time of the experience, final time
TimeInterval = 0.0 20.0

# theta scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 THETA_SCHEME

# implicit scheme, we need to solve a linear system a each time step
# resolution of the linear system with direct method
TypeSolver = DIRECT

# temporal dependance of the source
TemporalSource = HARMONIC 60.0

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous2D.x 4 4
