TypeElement = QUADRANGLE_LOBATTO
#TypeElement = QUADRANGLE_DG_LOBATTO
TypeEquation = ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# file where the ;esh is stored
FileMesh = coude_quad.msh

# order of space approximation
OrderDiscretization = 7

# boundary conditions (Neumann for lateral boundaries, absorbing at right, neumann at left)
ConditionReference = 1 3 5 6 NEUMANN
ConditionReference = 2 ABSORBING
ConditionReference = 4 NEUMANN

# inhomogeneous Neumann condition
TypeSource = SRC_SURFACE 4 UNIFORM Polarization 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputPlane = 0.0 40.0 4.0
# snapshots on all the mesh
SismoPlane = AUTO 100 100
# diffracted and total field (in this test case, we compute only total field)
FileOutputPlane = diffracTest.dat totalTimeCoude.dat

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
SismoMeshVolumetric = AUTO
# files where the snapshots on subdivided mesh are stored
FileOutputMeshVolumetric = diffrac_medit.bb total_TimeCoudeMesh.bb
# tbegin tend deltat 
ParametersOutputMeshVolumetric = 0.0 40.0 1.0

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 40.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_Coude.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint_Neu.dat
SismoPoint = 2.5 0.05
SismoPoint = 4.15 -3.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.001

# initial time of the experience, final time
TimeInterval = 0.0 10.0

# leap frog scheme on system of order 1
OrderTimeScheme = 4 LEAP_FROG_PML

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous2D.x 4 4
