Adimensionalization = YES
WavelengthAdim = 100e-9

# type of finite element
TypeElement = TRIANGLE_LOBATTO

# type of equation
TypeEquation = LAPLACE

# wavelength (used for helm2D)
WaveLength = 400e-9

# path where the meshes are stored
MeshPath = MAILLAGES/

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# Fichier de maillage
FileMesh = DemiDielecSquare.mesh

# pour les PML
AddPML = YES PML_XY+ 1.0 1
DampingPML = 3.0

# pour selectionner une partie des valeurs propres
SpectrumBox = 0.5 6.0
SpectrumRadius = 1e-6
NbEigenvaluesToCompute = 40
ShiftEigenvalue = (1.0,0.0)

FileEigenvalue = eigenvalSquare
DispersivePML = YES

DisplayEigenvectors = YES eigenvecDielecSquare

# order of space approximation (degre des polynomes)
OrderDiscretization = 10

StaticCondensation = YES Store

# boundary condition for edges of reference 3
ConditionReference = 3 DIRICHLET
ConditionReference = 2 NEUMANN

# dispersive material
MateriauDielec = 1 ISOTROPE 1.0 1.0 0.0
PhysicalMedia = Drude 2 TM Silicon

SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracCarre totalCarre

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (single or double precision)
OutputFormat = BINARY FLOAT

# we want to know the solution U only
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = mode2D.x 20 1
