# type of finite element
TypeElement = TRIANGLE_FIRST_FAMILY
# type of equation
TypeEquation = MODE_MAXWELL
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  ref_media  ref1 ref2 ref3 ref4
# nb_x : number of subdivisions along x
# ref_media reference of the elements (quadrilaterals or triangles)
# ref1, ref2, ref3, ref4 references of the edges y = ymin, x = xmax, y = ymax and x = xmin
FileMesh = mode_square.mesh

RefinementVertex = -9.677419354838709e-02 -1.161290322580645e-01 3 3.0
RefinementVertex = -9.677419354838709e-02 1.161290322580645e-01 3 3.0
RefinementVertex = 9.677419354838709e-02 1.161290322580645e-01 3 3.0
RefinementVertex = 9.677419354838709e-02 -1.161290322580645e-01 3 3.0

# order of space approximation 
OrderDiscretization = 7

# Dirichlet condition on E (and neumann condition on H)
ConditionReference = 1 SUPPORTED 0

# Eigenvalue = YES INVERT n nb_modes
# we search beta around omega*n
Eigenvalue = YES INVERT CENTERED 1.57 8

# we specify refractive index (epsilon = n^2)
MateriauDielec = 1 ISOTROPE SQUARE 1.44 1.0
MateriauDielec = 2 ISOTROPE SQUARE 3.48 1.0

# Pastix solver
TypeSolver = AUTO

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = test ModeMaxwellSquare

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

ExplicitMatrixFEM = YES

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = mode_maxwell.x 4 1
