# type of finite element
TypeElement = HEXAHEDRON_HCURL_LOBATTO

# type of equation
TypeEquation = TIME_MAXWELL_HDG

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0.0

# FileMesh = SPHERE a b nb_points
# creation of a mesh inside two spheres of radius a and b
# nb_points is number of points by unity
FileMesh = pave_inclusion.mesh

# order of space approximation 
OrderDiscretization = 5

# type of the mesh
TypeMesh = HEXA

# curved element
TypeCurve = B4F53 SPHERE

# static condensation is performed to have a smaller system to solve
StaticCondensation = YES Store

# boundary conditions for faces
ConditionReference = 2 DIRICHLET
ConditionReference = 3 ABSORBING

# MateriauDielec = ref ISOTROPE epsilon mu sigma 
# sigma is null if not present
MateriauDielec = 1 ISOTROPE 1.0 1.0
MateriauDielec = 2 ISOTROPE 4.0 2.0 0.1

#  surface source
TypeSource = SRC_SURFACE 2 GAUSSIAN 0.0 0.0 -1.0  5.0 8.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver used to solve Fi(x) = y
NonLinearSolver = MINPACK 1e-15 50

ParametersOutputGrille = 0 20.0 1.0
# snapshots on a 3-D regular grid 100x100x100
SismoGrille = 0.0 0.0 -0.1 AUTO 401 401 201
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracInclusionSphereAbc_ totalInclusionSphereAbc_

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# step time deltat
TimeStep = 0.005

# initial time of the experience, final time
TimeInterval = 0.0 20.1

# implicit scheme
#OrderTimeScheme = 4 LINEAR_SDIRK 1 Stable

# explicit scheme
OrderTimeScheme = 4 LINEAR_RUNGE_KUTTA 2

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 4

DataNonRegressionTest = time3D.x 8 48
