# finite element used
TypeElement = TETRAHEDRON_HP_FIRST_FAMILY

# for H(curl) formulation
TypeEquation = TIME_MAXWELL3D

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 0.25 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  ref_media  ref1 ref2 ref3 ref4
# nb_x : number of subdivisions along x
# ref_media reference of the elements (quadrilaterals or triangles)
# ref1, ref2, ref3, ref4 references of the edges y = ymin, x = xmax, y = ymax and x = xmin
FileMesh = coneSphere_cond.msh

# incident angle for plane wave
IncidentAngle = 90 -90

# order of space approximation
OrderDiscretization = 4

# boundary conditions
ConditionReference = 1 2 3 DIRICHLET
ConditionReference = 4 5 6 ABSORBING

# total field is computed
TypeSource = SRC_TOTAL_FIELD AUTO

# polarization of the plane wave
Polarization = 1.0 0 0

# solver used to solve finite element matrix
TypeSolver = DIRECT

# static condensation to remove internal dofs
StaticCondensation = YES Store

ParametersOutputGrille = 0 20.0 4.0
# snapshots on all the mesh
SismoGrille = 0.35 0.0 0.0 AUTO 200 200 200
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTimeConeMax.dat totalTimeConeMax.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# time step
TimeStep = 0.04

# time scheme used
OrderTimeScheme = 4 LINEAR_SDIRK 1

# time interval
TimeInterval = 0.0 20.1

# solver for mass matrix
ExplicitMassMatrix = YES
MassMatrixSolver = Direct 1

# temporal source
TemporalSource = RICKER

# we want only the solution E (electric field only)
ElectricOrMagnetic = -2

StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 4

DataNonRegressionTest = time3D.x 5 24


