# Gauss-Lobatto hexahedrals
TypeElement = HEXAHEDRON_HCURL_LOBATTO
# acoustic equation to be solved
TypeEquation = TIME_MAXWELL3D
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# FileMesh = SPHERE_CUBE a b 1/h
# where a is radius of the intern sphere
# outside boundary is the cube [-b,b]^3
# h is the space step
FileMesh = SPHERE_CUBE 1 2 3

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = 5

#PenalizationDG = -0.1 0.0

# boundary condition for edges of reference 3
ConditionReference = 1 NEUMANN
ConditionReference = 3 ABSORBING

MateriauDielec = 1 ISOTROPE 0.8 1.2 0.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN -1.5 0.0 0.0 0.6

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 10.0 1.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 100 100 100
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalTimeSphereNeuMax.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.01

# initial time of the experience, final time
TimeInterval = 0.0 5.0

# leap-frog scheme of order two
OrderTimeScheme = 4 RUNGE_KUTTA_LOW

AddPML = YES PML_XYZ 1.0 AUTO
DampingPML = 2.0

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = time3D.x 4 8
