# Gauss-Lobatto finite elements on hexahedrals
TypeElement = HEXAHEDRON_HCURL_LOBATTO
# acoustic equation to be solved
TypeEquation = TIME_MAXWELL3D
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# file where the mesh is stored
FileMesh = fente3D_all.mesh

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = 5

# boundary condition for edges of reference 3
ConditionReference = 1 DIRICHLET
ConditionReference = 2 3 ABSORBING

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 z0 radius
# where (x0, y0, z0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN -1.0 0 0 1

Polarization = 0 1 0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 20.0 4.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 101 101 101
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalTimeFente3D_Max.dat

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
# only surfacic mesh (referenced triangles and quadrangles)
SismoMeshSurfacic = 10 REFERENCE ALL
# files where the snapshots on subdivided mesh are stored
FileOutputMeshSurfacic = diffrac_surfFente_Max.bb total_surfTimeFente_Max.bb
ParametersOutputMeshSurfacic = 0.0 20.0 2.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U and gradients
ElectricOrMagnetic = -1

# steo time deltat
TimeStep = 0.02

# initial time of the experience, final time
TimeInterval = 0.0 20.0

# theta scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 4 RUNGE_KUTTA_LOW

# implicit scheme, we need to solve a linear system a each time step
# resolution of the linear system with direct method
TypeResolution = MUMPS

# temporal dependance of the source
TemporalSource = HARMONIC 60.0

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = time3D.x 4 8
