# type of finite element
TypeElement = TETRAHEDRON_DG_OPTIMAL
# type of equation
TypeEquation = TIME_MAXWELL3D_DG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 0.08 0.0
# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0.0

# file where mesh is written
FileMesh = balloonVolS7H7.meshb

# order of space approximation 
OrderDiscretization = 5

# penalization parameters
PenalizationDG = -0.1 -0.1

# boundary conditions for faces
ConditionReference = 1 2 DIRICHLET
ConditionReference = 3 ABSORBING

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_VOLUME GAUSSIAN -100 90 180 15.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

ParametersOutputGrille = 0 1001 24.0
# snapshots on a 3-D regular grid 100x100x100
SismoGrille = -100 25 250 AUTO 201 201 201
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracBalloon totalBalloonQ5_

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# steo time deltat
TimeStep = 0.04

# initial time of the experience, final time
TimeInterval = 0.0 301.0

# leap frog scheme
OrderTimeScheme = 4 RUNGE_KUTTA

# temporal dependance of the source
TemporalSource = SINUS_GAUSSIAN 0.001

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 4

DataNonRegressionTest = time3D.x 10 144
