# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY
# type of equation
TypeEquation = HARMONIC_MAXWELL
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
#Frequency = 0.25 0.0
# incident angle teta of the incident plane wave \vec{k} = (k sin(teta) cos(phi), k sin(teta) sin(phi), k cos(teta) )
# this angle is in degrees (0, 90, 180 by example)


TypeCurve = 3 CYLINDER 0 0 0 0 0 1 1.0
TypeCurve = 4 CYLINDER 0 0 0 0 0 1 1.75

# pour cylindrique
IncidentAngle = 90.0 0
# pour cartesien 
#IncidentAngle = 180.0 0

#FileMesh = Bicouche.mesh

# FileMesh = EXTRUDE nb_layers z0 z1 FichierMaillage  nb_cellules_z  nb_reference_maillage_2d   ref_laterale1 ref_laterale2 ... ref_lateralen \
#                   ref_top1 ref_top2 r... ref_topn     nb_reference_faces2d  ref_volume1 ref_volume2 ... ref_volume2
#FileMesh = EXTRUDE 1 -3.141592653589793 3.141592653589793 DisqueTransfinite.mesh  4    2  3  4  5 6     2  1 2
FileMesh = EXTRUDE 1 -1.0 1.0 DisqueTransfinite.mesh  3    2   3 4  5 6     2  1 2

#TypeCurve = 3 CIRCLE

#TransmissionExactSolution = YES 3

# order of space approximation 
OrderDiscretization = 5
OrdreTransmission = 1

Formulation2 = NO
# boundary conditions for edges of reference 3




# conditions limites pour le cylindre
ConditionReference = 4 ABSORBING
ConditionReference = 1 5 PERIODICITY
ConditionReference = 2 6 PERIODICITY

# condition de transmission
ReferenceTransmission = 3 PARAM (-0.60090982,-0.019055153) (-4.3187676e-13,4.1376997e-34) (3,-7.7027605e-35) (3,-3.9381992e-35) (9,0.47746483) (9,0.47746483) 0 0.05

ThresholdMatrix = 1e-12

OmegaMinusPlus = 2 1

MateriauDielec = 1 ISOTROPE 1 1
MateriauDielec = 2 ISOTROPE 1 1


# plane wave source
TypeSource = SRC_TOTAL_FIELD PLANE_WAVE


# dipole oriented along e_z (E0)
Polarization = 0 0 1

TypeSolver = DIRECT

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 0.0 0.0 0.0 AUTO 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTestApprocheEx totalTestApprocheEx

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO Ah.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell3D.x 0 1
