# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY
# type of equation
TypeEquation = HARMONIC_MAXWELL
# path where the meshes are stored
MeshPath = ./
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
#Frequency = 0.25 0.0
# incident angle teta of the incident plane wave \vec{k} = (k sin(teta) cos(phi), k sin(teta) sin(phi), k cos(teta) )
# this angle is in degrees (0, 90, 180 by example)


TypeCurve = 5 CYLINDER 0 0 0 0 0 1 0.25
TypeCurve = 3 CYLINDER 0 0 0 0 0 1 1
TypeCurve = 4 CYLINDER 0 0 0 0 0 1 1.75

# pour cylindrique
IncidentAngle = 90.0 0
# pour cartesien 
#IncidentAngle = 180.0 0

#FileMesh = Bicouche.mesh

# FileMesh = EXTRUDE nb_layers z0 z1 FichierMaillage  nb_cellules_z  nb_reference_maillage_2d   ref_laterale1 ref_laterale2 ... ref_lateralen \
#                   ref_top1 ref_top2 r... ref_topn     nb_reference_faces2d  ref_volume1 ref_volume2 ... ref_volume2
#FileMesh = EXTRUDE 1 -3.141592653589793 3.141592653589793 DisqueTransfinite.mesh  4    2  3  4  5 6     2  1 2
#FileMesh = EXTRUDE 1 -1.0 1.0 mesh/DisqueTransfinite.mesh  3    2  3  4  5 6     2  1 2
FileMesh = EXTRUDE 1 -1.0 1.0 MAILLAGES/DoubleDisqueTrou.mesh  3    3  3 4 5  6 7 0  2  1 2

#TypeCurve = 3 CIRCLE

#TransmissionExactSolution = YES 3

# order of space approximation 
OrderDiscretization = 5
OrdreTransmission = 1

Formulation2 = NO
# boundary conditions for edges of reference 3




# conditions limites pour le cylindre
#ConditionReference = 1 2 4 5 6  ABSORBING
#ConditionReference = 1 2 4 5 6  DIRICHLET
#ConditionReference = 1 2 5 6  DIRICHLET
ConditionReference = 5 DIRICHLET
ConditionReference = 4 ABSORBING
ConditionReference = 1 6 PERIODICITY
ConditionReference = 2 7 PERIODICITY
#ReferenceTransmission = ref PARAM A B D1_11 D1_22 D2_11 D2_22 Decalage delta= 2 * pi R_0/ N (ici pour N =32)
ReferenceTransmission = 3 PARAM -0.12281977 -0.12281977 0.14158378 0.14158378 0.14158378 0.14158378  0 9.817477042468103e-02
#ReferenceTransmission = 3 PARAM -0.11555188 -0.11555188 0.13199746 0.13199746 0.13199746 0.13199746
#ReferenceTransmission = 3 PARAM -0.12286 -0.12286 0.141583 0.141583 0.141583 0.141583 0  0.196349540849362
#ReferenceTransmission = 3 PARAM -0.12286 -0.12286 0.141583 0.141583 0.141583 0.141583 0  9.817477042468103e-02
#ReferenceTransmission = 3 PARAM -0.87718133 -0.87718133 -0.71683383 -0.71683383 -0.71683383 -0.71683383  0 0.196349540849362
#ReferenceTransmission = 3 PARAM 0 0 0 0 0 0 0 0.02
#ReferenceTransmission = 3 PARAM 0.5 0.43 0.22 0.195 0.195 0.23 0.1 0.02


ThresholdMatrix = 1e-12

OmegaMinusPlus = 2 1

MateriauDielec = 1 ISOTROPE 1 1
MateriauDielec = 2 ISOTROPE 1 1


# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
#TypeSource = SRC_VOLUME GAUSSIAN 1.5 1.5.0 0.0 0.2
TypeSource = SRC_TOTAL_FIELD PLANE_WAVE
#TypeSource = SRC_TOTAL_FIELD GAUSSIAN_BEAM Waist 2.0

# dipole oriented along e_x (E0)
Polarization = 0 1 0
#Polarization = 1.0 0.0 0.
# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 0.0 0.0 0.0 AUTO 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTestApprocheCylinder totalTestApprocheCylinder

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO Ah.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = maxwell3D.x 0 1
