# type of finite element
TypeElement = TRIANGLE_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL2D

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 0.98 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file containing the mesh
FileMesh = carre.mesh

# order of approximation 
OrderDiscretization = 5

# Silver-Muller absorbing boundary condition
ConditionReference = 1 2 3 4 ABSORBING

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 1.0

# source oriented along e_x
Polarization = 1 0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracCarreMax2D totalCarreMax2D

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell2D.x 0 8
