# type of finite element
TypeElement = TRIANGLE_HP_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL2D

# path where the meshes are stored
MeshPath = ./

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 180.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = REGULAR 21 -4.0 4.0   -4.0 4.0   1   1 2 3 4

# order of space approximation 
OrderDiscretization = 8

# PML layers around the domain
AddPML = YES PML_XY 1.0 AUTO
DampingPML = 4.0

# refinement around the source
RefinementVertex = 0.0 0 4 2.0

# boundary conditions
ConditionReference = 1 2 3 4 DIRICHLET

# Dirac 
TypeSource = SRC_DIRAC

# origin of the Dirac
OriginePhase = 0.0 0.0 0.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# output on a plane
SismoPlane = AUTO 200 200
FileOutputPlane = diffracTest totalDiracMax2D

# we want to know the solution U only
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell2D.x 0 8
