
######################################
# probleme de cellule 3D 
####################################

# type of finite element
TypeElement = TETRAHEDRON_LOBATTO
# type of equation
TypeEquation = CELLULAIRE_PERIODIQUE

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
# pour le trou
#FileMesh = CellulePer3D.mesh
#FileMesh = cell_final.mesh
FileMesh = cell_sphere.mesh

CelluleSymetrique = false

# order of space approximation 
OrderDiscretization = 4

# troncature et rayon moyen pour le problemes cellulaires
Troncature = 2
RayonMoyen = 1

PenalisationLaplacien = -1e-10

TypeCurve = 1 SPHERE

# epsilon mu sigma
MateriauDielec = 1 ISOTROPE 1.0 1.0  0.0
MateriauDielec = 2 ISOTROPE 1.0 1.0 0.0
MateriauDielec = 3 ISOTROPE 2.0 2.0 0.0

# conditions limites
ConditionReference = 2 7 PERIODICITY
ConditionReference = 3 6 PERIODICITY
ConditionReference = 4 5 ABSORBING

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve
NonLinearSolver = MINPACK 1e-15 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 0.0 0.0 0.0 -0.5 0.5 -0.5 0.5 -2 2 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = SolCelluleP1SphereLayer SolCelluleP2SphereLayer

OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = CellulairePeriodique3D.x 0 1


