
######################################
# probleme de cellule 3D 
####################################

TypeEquation = CELLULAIRE_PERIODIQUE

# type of finite element
TypeElement = TETRAHEDRON_LOBATTO

# path where the meshes are stored
MeshPath = ./

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# extrusion of a regular mesh of a square
# domain 1 is comprised between -5 < z < -0.5 and 0.5 < z < 5.0
# domain 2 is comprised between -0.5 < z < 0.5
# actually for the definition of cellular problems, the hetereogeneities
# are assumed to be comprised between -0.5 < z < 0.5
FileMesh = EXTRUDE 3 -5 -0.5 0.5 5 MAILLAGES/regularN5.mesh 4 3 4 4 \
                   3 4 5 6  0 0 0 0 \
                   3 4 5 6  0 0 0 0 \
                   3 4 5 6  2 0 0 0 \
                   1  1 2 1

# we have meshed both negative and positive part => non-symmetric case
# symmetric case is not implemented in 3-D
CelluleSymetrique = false

# order of space approximation 
OrderDiscretization = 4

# troncature for DtN operator (absorbing condition)
Troncature = 2
# R0
RayonMoyen = 1

# parameter epsilon, in equation  -Delta u  - epsilon u = 0
PenalisationLaplacien = -1e-10

# epsilon mu sigma as entered in Maxwell's equations
# outside region -0.5 < z < 0.5, epsilon = mu = 1, and sigma = 0
MateriauDielec = 1 ISOTROPE 1.0 1.0  0.0
# in the region of hetereogeneity, you can specifiy epsilon, mu and sigma
MateriauDielec = 2 ISOTROPE 5.0 10.0 4.0

# periodic conditions between x = xmin and x = xmax (idem for y = ymin, y = ymax)
ConditionReference = 3 5 PERIODICITY
ConditionReference = 4 6 PERIODICITY

# absorbing boundary condition for z = zmin and z = zmax
ConditionReference = 1 2 ABSORBING

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver used for inversion of Fi
NonLinearSolver = MINPACK 1e-15 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 0.0 0.0 0.0 -0.5 0.5 -0.5 0.5 -2 2 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = SolCelluleP1ThinLayer SolCelluleP2ThinLayer
OutputFormat = BINARY DOUBLE

# we want to know the solution U only
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = CellulairePeriodique3D.x 0 1

