# intervalle de temps de la simulation
TimeInterval = 0 0.1
TimeStep = 1e-6

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)
DisplayFrequency = 1e-4
  
# parametres physiques de la corde
# String = L A rho T0 E I G k_prime amo(0) amo(1) rho_relax Nx is_sruck K_hammer R_hammer
# Corde C2, on prend d = 1.1227e-3, K article = 4e8
String = 1.60 9.8995927e-7 24085 1042  2.02e+11  7.79874624e-14 8e10 0.85 0.02384 0.02384 1.0 100 1 5e9 0
String = 1.60 9.8995927e-7 24085 1046  2.02e+11  7.79874624e-14 8e10 0.85 0.02384 0.02384 1.0 100 1 5e9 0
String = 1.60 9.8995927e-7 24085 1048  2.02e+11  7.79874624e-14 8e10 0.85 0.02384 0.02384 1.0 100 1 5e9 0

# excitation par une force donnee dans un fichier
Hammer = FORCE EXPERIMENT example/multi_string/ForceExt48kH.dat  0.127 0.02 2011 2.08333e-5

# Marteau = YES masse point_impact vitesse p epaisseur pente deltatForce eloignement epsilon
# Hammer = YES 9.8e-3 0.2 1.5 2.3 0.02 2011 0.02 -0.02001  1e-10

# parametres de discretisation en temps
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25
StringPermutations = PERMUT_ALL

# donnees initiales sur la corde
StringInitialData = NONE

# interpolation sur une grille reguliere
#StringInterp = 200
#StringInterpTimeGrid = 0 0.35 1e-4

# sismogramme d'un point de la corde
StringSismo = 0.06 0.06 0.06
StringSismoTimeGrid = 0  1 2e-5     100

DirectoryOutputString = ./

FileOutputString = SismoLM_C2.txt SismoHammerC2.txt ForceMarteauC2.txt EnergyNoteC2.txt
FileOutputSismoString = SismoStringC2_ SismoLastPointC2_ SismoCrushC2_ ValC2_

# sortie d'un fichier avec l'energie
Energy = 0 1.0 1e-4 1

# parametre de convergence de la methode de Newton
NewtonParam = 1e-12 20 1e-9

# angle au chevalet
Bridge = 2 2 2

DataNonRegressionTest = multistringStiffNL.x 0 1
