# intervalle de temps de la simulation
TimeInterval = 0 0.1
TimeStep = 1e-6

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)
DisplayFrequency = 1e-4
  
# parametres physiques de la corde
# String = L A rho T0 E I G k_prime PHI_DAMPING b0_u b0_v b0_phi b2_u b2_v b2_phi Nx is_sruck K_hammer R_hammer
# Corde D#1, on prend d = 1.4833e-3
String = 0.62  8.0864739e-7  7850 670 2.0e11  5.203655319e-14  8e10  0.85  PHI_DAMPING 0.25 0.5 0.25 4e-9 1e-9 4e-9   1.0 100 1  4.5e9 0
String = 0.62  8.0864739e-7  7850 669 2.0e11  5.203655319e-14  8e10  0.85  PHI_DAMPING 0.25 0.5 0.25 4e-9 1e-9 4e-9   1.0 100 1  4.5e9 0
String = 0.62  8.0864739e-7  7850 671 2.0e11  5.203655319e-14  8e10  0.85  PHI_DAMPING 0.25 0.5 0.25 4e-9 1e-9 4e-9   1.0 100 1  4.5e9 0

# Marteau = YES masse point_impact vitesse p epaisseur pente deltatForce eloignement epsilon
Hammer = YES 8.91e-3 0.0744 1.5 2.5 0.02 2011 0.02 -0.02001  1e-10

# parametres de discretisation en temps
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25
StringPermutations = PERMUT_ALL

# donnees initiales sur la corde
StringInitialData = NONE

# interpolation sur une grille reguliere
#StringInterp = 400
#StringInterpTimeGrid = 0 0.35 1e-3

# sismogramme d'un point de la corde
StringSismo = 0.1144 0.1144 0.1144
StringSismoTimeGrid = 0  1 2e-5     100

DirectoryOutputString = ./

FileOutputString = SismoLM_C4.txt SismoHammerC4.txt ForceMarteauC4.txt EnergyNoteC4.txt
FileOutputSismoString = SismoStringC4_ SismoLastPointC4_ SismoCrushC4_ ValC4_

# sortie d'un fichier avec l'energie
Energy = 0 1.0 1e-4 1

# parametre de convergence de la methode de Newton
NewtonParam = 1e-12 20 1e-9

# angle au chevalet
Bridge = 4 4 4

DataNonRegressionTest = multistringStiffNL.x 0 1
