# intervalle de temps de la simulation
TimeInterval = 0 0.1
TimeStep = 1e-6

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)
DisplayFrequency = 1e-4
  
#PlanCordes = AUTO
PlanCordes = example/PIANO/plandecordes.dat

# String = Note coef_desaccord nb_points is_struck K R
String = Dd1 0 1.0 200 1 1e9 1e4

# Hammer = NO pour une condition initiale
Hammer = NO

# parametres de discretisation en temps
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25
StringPermutations = PERMUT_ALL

# donnees initiales sur la corde
StringInitialData = SINUS 1e-3 2 0

# interpolation sur une grille reguliere
StringInterp = 400
StringInterpTimeGrid = 0 0.1 5e-3

# sismogramme d'un point de la corde
StringSismo = 1.25
StringSismoTimeGrid = 0  10.0 4e-5     100

DirectoryOutputString = ./

FileOutputString = SismoLM_Dd1.txt SismoHammerDd1.txt ForceMarteauDd1.txt EnergyNoteDd1.txt
FileOutputSismoString = SismoStringDd1_ SismoLastPointDd1_ SismoCrushDd1_ ValDd1_

# sortie d'un fichier avec l'energie
Energy = 0 10.0 1e-4 1

# parametre de convergence de la methode de Newton
NewtonParam = 1e-9 20 1e-9 YES_SCALE 1e-3

# angle au chevalet
Bridge = ATTACHED

DataNonRegressionTest = multistringStiffNL.x 0 1
