# intervalle de temps de la simulation
TimeInterval = 0 0.1
TimeStep = 1e-6

# intervalle de temps auquel les informations sont donnees (energie, temps de calcul)
DisplayFrequency = 1e-4
  
#PlanCordes = AUTO
PlanCordes = example/PIANO/plandecordes.dat

# String = Note coef_desaccord nb_points is_struck K R
String = Gd1 1e-3 1.0 200 1 1e9 1e4
String = Gd1 -1e-3 1.0 200 1 1e9 1e4

# excitation par une force donnee dans un fichier
#Hammer = FORCE EXPERIMENT ForcesExt/IRCAM/Dd1/ForceExt48kHessai2.dat  0.25 0.02 2011 2.0833e-05

# Marteau = YES masse point_impact vitesse p epaisseur pente deltatForce eloignement epsilon
#Hammer = YES 1.2e-2 0.25 1.5 1.8 0.02 2011 0.02 -0.02001  1e-10
Hammer = Gd1 0.5

# parametres de discretisation en temps
StringSolver = THETA_NL_QUARTER  0.0833333333 0.25
StringPermutations = PERMUT_ALL

# donnees initiales sur la corde
StringInitialData = NONE

# interpolation sur une grille reguliere
#StringInterp = 400
#StringInterpTimeGrid = 0 0.35 1e-3

# sismogramme d'un point de la corde
StringSismo = 1.749 1.749
StringSismoTimeGrid = 0  10.0 2e-5     100

DirectoryOutputString = ./

FileOutputString = SismoLM_Gd1.txt SismoHammerGd1.txt ForceMarteauGd1.txt EnergyNoteGd1.txt
FileOutputSismoString = SismoStringGd1_ SismoLastPointGd1_ SismoCrushGd1_ ValGd1_

# sortie d'un fichier avec l'energie
Energy = 0 10.0 1e-4 1

# parametre de convergence de la methode de Newton
NewtonParam = 1e-9 20 1e-9 YES_SCALE 1e-3

# angle au chevalet
Bridge = 2 2

DataNonRegressionTest = multistringStiffNL.x 0 1
