# type of finite element
TypeElement = TRIANGLE_RADAU

# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 2.0 0.0

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 180.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = REGULAR 11 0.0 4.0 -4.0 4.0  1  1 2 3 4

# order of space approximation 
OrderDiscretization = 10

# pour avoir une matrice de masse diagonale sans zeros
ForceDiagonalMass = YES

# NumberModes = SINGLE n
NumberModes = 0

# absorbing boundary condition
ConditionReference = 1 2 3 ABSORBING

# On the axis, a fictitious Neumann boundary condition is set
ConditionReference = 4 NEUMANN

# MateriauDielec = ref ISOTROPE rho mu sigma
MateriauDielec = 1 ISOTROPE 1.2 1.5 0.0

# PML layers (does not work with acous_axi)
#AddPML = YES PML_X+Y 1.0 AUTO
#DampingPML = 2.0

# Gaussian source
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 0.0  0.5 1.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = DIRECT

ParametersOutputGrille = 0.0 10.0 2.0
# snapshots on three planes intersecting at (0, 0, 0)
SismoGrille = 0 0 0 AUTO 200 200 200
# files where the diffracted and total field will be stored
FileOutputGrille = diffracTestGhost totalTimeCarreAxi

ParametersOutputPlaneAxi = 0.0 20.0 1.0
# snapshot on a 3-D parallelogram
# of extremity (x0, y0, z0) and with the two points (x1, y1, z1), (x2, y2, z2)
# these two points are the extremities adjacent to the first extremity
# SismoPlaneAxi = x0 y0 z0 x1 y1 z1 x2 y2 z2 nx ny
SismoPlaneAxi = -4.0 0.0 -4.0  4.0 0.0 -4.0  -4.0 0.0 4.0   200 200
# files where the outputs on planes are written
FileOutputPlaneAxi = diffracTestGhost totalTimePlaneAxi


# we want to know the solution U only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# on stocke la matrice en attendant mieux
ExplicitMatrixFEM = YES

# time step deltat
TimeStep = 0.005

# initial time of the experience, final time
TimeInterval = -0.5 10.1

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
#OrderTimeScheme = 4 RUNGE_KUTTA_NYSTROM YES
OrderTimeScheme = 4 LEAP_FROG

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = acous_axi.x 10 8
