TypeElement = TETRAHEDRON_LOBATTO
TypeEquation = TIME_FLUID_STRUCTURE
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

FileMesh = Bicouche3D_Grand.mesh

# order of space approximation
OrderDiscretization = 8

# boundary conditions
FluidConditionReference = 1 ABSORBING
SolidConditionReference = 1 NEUMANN
ConditionReference = 4 NEUMANN

# properties for the solid (ISOTROPE rho lambda mu)
SolidMateriauDielec = 2 ISOTROPE 1.0 3.5 1.5

# properties for the fluid (ISOTROPE rho mu sigma)
FluidMateriauDielec = 1 ISOTROPE 1.0 1.0 0.0

# references for the fluid
ReferenceFluid = 1

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
FluidTypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 2.0 1.2

FluidPolarization = 1.0 0.0 0.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
FluidParametersOutputGrille = 0.0 10.0 2.0
# snapshots on all the mesh
FluidSismoGrille = 0 0 0 AUTO 200 200 200
# diffracted and total field (in this test case, we compute only total field)
FluidFileOutputGrille = diffracTest.dat totalFluid.dat

SolidParametersOutputGrille = 0.0 10.0 2.0
# snapshots on all the mesh
SolidSismoGrille = 0 0 0 AUTO 200 200 200
# diffracted and total field (in this test case, we compute only total field)
SolidFileOutputGrille = diffracTest.dat totalSolid.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# sismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the pressure and x-displacement
ElectricOrMagnetic = 0

# step time deltat
TimeStep = 0.01

# initial time of the experience, final time
TimeInterval = 0.0 12.1

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 LEAP_FROG_PML
#OrderTimeScheme = 4 RUNGE_KUTTA_LOW

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = fluid_structure.x 10 8
