TypeElement = QUADRANGLE_LOBATTO
TypeEquation = TIME_VIBRO
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 340.0 0.0

# mesh file
AcousticFileMesh = PlateCube.mesh

# order of space approximation
AcousticOrderDiscretization = 7
MecanicOrderDiscretization = 5

# boundary condition for edges of reference 3
AcousticConditionReference = 1 NEUMANN
AcousticConditionReference = 3 ABSORBING

MecanicConditionReference = 1 DIRICHLET

# several choices for selecting properties of a media 
# MateriauDielec = ref ISOTROPE rho lambda mu
# MateriauDielec = ref YOUNG_POISSON rho E nu
MecanicMateriauDielec = 1 YOUNG_POISSON 2700 6.9e10 0.33

# speed of sound and density of air
Velocity = 340.0
Density = 1.29

# thickness of the plate
MecanicThicknessPlate = 0.1

# reference(s) of the plate
ReferencePlate = 1

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
#AcousticTypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 1.0 1.0
#MecanicTypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 1.404864536324933
MecanicTypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 1.4
MecanicPolarization = 0 0 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
MecanicParametersOutputPlane = 0.0 0.1 1e-3
# snapshots on all the mesh
MecanicSismoPlane = AUTO 251 251
# diffracted and total field (in this test case, we compute only total field)
MecanicFileOutputPlane = diffracTest.dat CarrePlate.dat

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
AcousticParametersOutputGrille = 0.0 10.0 1e-3
# snapshots on all the mesh
AcousticSismoGrille = 0 0 0.01 AUTO 100 100 100
# diffracted and total field (in this test case, we compute only total field)
AcousticFileOutputGrille = diffracTest.dat CubePlate.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the solution U (not the gradient)
ElectricOrMagnetic = -1

# steo time deltat
TimeStep = 2e-6

# initial time of the experience, final time
TimeInterval = 0.0 2e-2

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 2 LEAP_FROG

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = vibro.x 10 1
