# type of finite element
TypeElement = TRIANGLE_RADAU
# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 2.1e6 0.0

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 180.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = disqueRaffHelio.mesh

# order of space approximation 
OrderDiscretization = 10

# RefinementVertex = x y level ratio
# mesh is refined close to vertex x y
RefinementVertex = 0 0.8 3 2.0

# curved element
TypeCurve = 4 CIRCLE

# only mode m = 0 is considered
NumberModes = SINGLE 0

# boundary condition on the extern sphere
ConditionReference = 4 ABSORBING

# On the axis, a fictitious Neumann boundary condition is set
ConditionReference = 2 NEUMANN

# coefficients depending on r only
MateriauDielec = 1 ISOTROPE RADIAL example/helm_radial/rho.don 0.0 1.0 \
                            RADIAL example/helm_radial/mu.don 0.0 1.0 \
                            RADIAL example/helm_radial/sigma.don 0.0 1.0

# Dirac source
TypeSource = SRC_DIRAC

# origin of the Dirac
OriginePhase = 0 0 0.8

# polarization E0 of the plane wave
Polarization = 1.0 0 0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = DIRECT

# O is the origin, A and B two points of the plane
# such that the plane is described by O + t OA + u OB
#  where t and u describe the interval [0, 1]
#SismoPlaneAxi = xO yO zO  xA yA zA  xB yB zB  nx ny
SismoPlaneAxi = -1.0007126 0.0 -1.0007126   1.0007126 0.0 -1.0007126  -1.0007126 0.0 1.0007126   600 600
FileOutputPlaneAxi = diffracPlaneAxiHelio totalPlaneAxiHelio

# we want to know the solution U only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz_axi.x 0 8
