# type of finite element
TypeElement = QUADRANGLE_LOBATTO

# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 0.25 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0 0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = disque_aniso_helio.mesh

# order of space approximation 
OrderDiscretization = 10

# mode m=2 is selected
NumberModes = SINGLE 2

ThresholdMatrix = 1e-30

# curved element
TypeCurve = 3 CIRCLE

# boundary conditions
ConditionReference = 2 NEUMANN
ConditionReference = 3 DIRICHLET

# physical coefficients
PhysicalMedia = rho 1 ISOTROPE SAME_MESH MAILLAGES/disque_aniso_helio.mesh 0.0 1.0 DATA/rhoHelmAxiAniso.don 10 1.6
PhysicalMedia = mu 1 ANISOTROPE SAME_MESH MAILLAGES/disque_aniso_helio.mesh 0.0 1.0 DATA/mu_rr_HelmAxiAniso.don 10 1.6 \
                                SAME_MESH MAILLAGES/disque_aniso_helio.mesh 0.0 1.0 DATA/mu_rz_HelmAxiAniso.don 10 1.6 \
                                0.0 \
                                SAME_MESH MAILLAGES/disque_aniso_helio.mesh 0.0 1.0 DATA/mu_zz_HelmAxiAniso.don 10 1.6 \
                                0.0 \
                                SAME_MESH MAILLAGES/disque_aniso_helio.mesh 0.0 1.0 DATA/mu_teta_HelmAxiAniso.don 10 1.6

PhysicalMedia = sigma 1 ISOTROPE SAME_MESH MAILLAGES/disque_aniso_helio.mesh 0.0 1.0 DATA/sigma_HelmAxiAniso.don 10 1.6

# gaussian source
TypeSource = SRC_VOLUME GAUSSIAN 1.0 0 1.0 1.0 2.0

Polarization = 1.0 0 0.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlaneAxi = 1e-12 0.0 -4.0  4.0 0.0 -4.0   1e-12 0.0 4.0  100 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlaneAxi = diffracAnisoHelmAxi totalAnisoHelmAxi

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz_axi.x 0 8
