# type of finite element
TypeElement = TRIANGLE_CLASSICAL
# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 0.25 0.0

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 90.0 -90.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = couronne_disque_quad.mesh

# order of space approximation 
OrderDiscretization = 10

# curved element
TypeCurve = 1 CIRCLE
TypeCurve = 3 CIRCLE

# NumberModes = AUTO threshold
NumberModes = 30

# absorbing boundary condition 
ConditionReference = 3 ABSORBING
# On the axis, a fictitious Neumann boundary condition is set
ConditionReference = 2 4 NEUMANN
# Dirichlet condition
ConditionReference = 1 DIRICHLET

MateriauDielec = 1 ISOTROPE 50.0 2.0 0.0

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_TOTAL_FIELD PLANE_WAVE

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = DIRECT

# snapshots on three planes intersecting at (0, 0, 0)
SismoGrille = 0 0 0 AUTO 200 200 200
# files where the diffracted and total field will be stored
FileOutputGrille = diffracSphereAxiHelmDirichlet totalSphereAxiHelmDirichlet

# we want to know the solution U only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz_axi.x 0 8

