# type of finite element
TypeElement = TRIANGLE_RADAU

# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 180.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = ellipse_axi.mesh

# order of space approximation 
OrderDiscretization = 10

# curved element
TypeCurve = 1 ELLIPSE 0.0 0.0 2.0 4.0
TypeCurve = 3 ELLIPSE 0.0 0.0 2.5 4.75

# axial incidence
NumberModes = SINGLE 0

# PML are added for y < ymin and y > ymax
# and x > xmax (since we consider half-plane region in axisymmetric computation)
#AddPML = YES PML_X+Y 1.0 AUTO
#DampingPML = 4.0

# MateriauDielec = 1.0 ISOTROPE 2.0 3.0 0
MateriauDielec = 1.0 ISOTROPE 2.0 3.0

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 3 ABSORBING

# CURVE -> we put curvature terms in absorbing boundary conditions
ModifiedImpedance = CURVE

# OrderAbsorbingBoundaryCondition = order PARAMETERS gamma theta zeta
OrderAbsorbingBoundaryCondition = 6 PARAMETERS 0.25 0.4 0.2

# if YES, finite element is symmetric even for grazing abc
GibcSymmetric = YES

# On the axis, a fictitious Neumann boundary condition is set
ConditionReference = 2 4 NEUMANN

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# snapshots on three planes intersecting at (0, 0, 0)
SismoGrille = 0 0 0 AUTO 200 200 200
# files where the diffracted and total field will be stored
FileOutputGrille = diffracEllpiseAxiCla6 totalEllipseAxiCla6

# we want to know the solution U only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz_axi.x 0 1
