# type d'equation
TypeEquation = LAPLACE

# type d'element fini
TypeElement = TRIANGLE_LOBATTO

# ordre de discretisation
OrderDiscretization = 1

# type de maillage
TypeMesh = TRI

# pour afficher une courbe de dispersion
# DisplayPlot = kx1 ky1  kx2 ky2  LOG log_min fichier nb_points
DisplayPlot = 0 0  4.0 0.0 LOG -2 dispersion.dat 200

# fichier de maillage (du motif)
# si un fichier .mesh, mettre les vecteurs du motif periodique
# exemple : FileMesh = motif.mesh ux uy  vx vy
# pour un maillage reguliere :
# FileMesh = REGULAR angle 
FileMesh = REGULAR 60

# pour avoir l'ordre de dispersion
FindOrder = YES 0.1 0.2

# PenalizationDG a revoir pour DG




