# adimensionalisation
Adimensionalization = YES

# parameter for z0 (usually wavelength)
WavelengthAdim = 1e-6

# NonLinearSusceptibility = gammaNL
NonLinearSusceptibility = 9.3252306e-31

# RefractiveIndex = eps_inf nb_materiau alpha0 lambda0 alpha1 lambda1 ...
# wavelengths lambda0, lambda1 are expressed in micrometers
RefractiveIndex = 1.44 1 1.02408 4.5

# writes the solution in time and frequency domain for different values of z
# DisplayZ = z0 zmax dz
DisplayZ = 0.0 800e-6 200.0e-6

# is YES, the envelope is written in time-domain outputs
AfficheEnveloppe = YES

# File where the sismos are written
FileOutputDisplayZ = EnUppeBF2_.dat

# PropagationStep = dz
PropagationStep = 0.1e-6

# PropagationInterval zmax
PropagationInterval = 800e-6

# Scheme used for evolution in z
OrderTimeScheme = 4 RUNGE_KUTTA

# TimeImpulsion = nb_points_time padding_time Gaussian tau Tmax amplitude
#TimeImpulsion = 2200 0 GaussianHalf 80.0e-15 2000e-15 2.0e8
TimeImpulsion = 100000 0 GaussianHalf 80.0e-15 2000e-15 1.73205e8

# Polarization : Linear, Circular or Elliptic
# Polarization = Elliptic Ex Ey phi_x phi_y
#Polarization = Linear
Polarization = Circular

# Uppe : exact model in 1-D
SchrodingerModel = UPPE

# Wavelength in vaccum
Wavelength = 0.8e-6

# values epsilon(omega) beyond the interval are not treated (the frequency is not treated)
IntervalEpsilon = 0 100

# if YES, negative values of epsilon(omega) are forbidden
#ForbidNegativeIndex = YES

# FourierTransform = SHIFTED_SINGLE, TIME_CENTER or ODD_FREQUENCIES
#FourierTransform = SHIFTED_SINGLE
FourierTransform = TIME_CENTER

# verbosity level
PrintLevel = 4

# data for non-regression tests
DataNonRegressionTest = schrodinger1D.x 4 1
