# adimensionalisation
Adimensionalization = YES

# parameter for z0 (usually wavelength)
WavelengthAdim = 1e-6

# NonLinearSusceptibility = gammaNL
NonLinearSusceptibility = 2.0e-32

# RefractiveIndex = eps_inf nb_materiau alpha0 lambda0 alpha1 lambda1 ...
# wavelengths lambda0, lambda1 are expressed in micrometers
# RefractiveIndex = DampedMaterial eps_inf nb_mat alpha0 lambda0 T0 alpha1 lambda1 T1 ...
RefractiveIndex = DampedMaterial 1.44 1 1.02408 4.5 1.0e-11

# is YES, the envelope is written in time-domain outputs
DisplayZ = 0.0 0.001 2.0e-4

# File where the sismos are written
AfficheEnveloppe = YES

# File where the sismos are written
FileOutputDisplayZ = EnUppeDamped.dat

# PropagationStep = dz
PropagationStep = 1.0e-6

# PropagationInterval zmax
PropagationInterval = 0.001

# Scheme used for evolution in z
OrderTimeScheme = 4 RUNGE_KUTTA

# TimeImpulsion = nb_points_time padding_time Gaussian tau Tmax amplitude
#TimeImpulsion = 2200 0 GaussianHalf 80.0e-15 2000e-15 2.0e8
#TimeImpulsion = 24000 0 GaussianHalf 120.0e-15 2000e-15 2.0e8
TimeImpulsion = 1000 0 GaussianHalf 120.0e-15 2000e-15 2.0e8

# Polarization : Linear, Circular or Elliptic
# Polarization = Elliptic Ex Ey phi_x phi_y
#Polarization = Linear
Polarization = Elliptic 1.2 0.35  40 65

# Uppe : exact model in 1-D
SchrodingerModel = UPPE

# Wavelength in vaccum
Wavelength = 0.92e-6

# values epsilon(omega) beyond the interval are not treated (the frequency is not treated)
IntervalEpsilon = 0 100

# if YES, negative values of epsilon(omega) are forbidden
#ForbidNegativeIndex = YES


#FourierTransform = SHIFTED_SINGLE
#FourierTransform = TIME_CENTER
#FourierTransform = ODD_FREQUENCIES number_of_odd_frequencies
FourierTransform = ODD_FREQUENCIES 3

# verbosity level
PrintLevel = 4

# data for non-regression tests
DataNonRegressionTest = schrodinger1D.x 5 1
