# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
# frequence adimensionnelle = 60 Hz / 3e8 = 2e-7
Frequency = 2e-4 0.0
#Frequency = 2e-3 0.0

# fichier de maillage
FileMesh = NewDemiDisqueThreeLayersVeryAcc10.mesh
//FileMesh = DemiDisqueThreeAccurateLayers20.mesh
//FileMesh = DemiDisqueThreeLayers2.mesh
//FileMesh = DemiDisqueThreeLayers04.mesh

Ray = 10.0


# courbes presentes
TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 5 CIRCLE

ReferenceDirichlet = 5

MateriauDielec = 2 ISOTROPE 1.0 1.0 2.18e7
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0
MateriauDielec = 1 ISOTROPE 1.0 300.0 5.462e5
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.88e0

# bords
#ReferenceBord = 5

#Eigensolver = Polynomial
Eigensolver = Nleigs Split
TypeProblem = 4NDD
Condition = Sotor
#Condition = Dirichlet Non_Linear
#Condition = Neumann Linear
#Condition = BGT1 Non_Linear
#Condition = BGT2 Non_Linear
#Condition = BGT2 Linear 5

# order of space approximation
OrderDiscretization = 4

# snapshots on a 2-D regular grid 200x200
SismoPlane = -0.22 0.22 -0.22 0.22 201 201
#SismoPlane = AUTO 200 200
SismoLine = 0.0 2.0 0.0 0.0 10001

OnlyEz = NO
ShiftEigenvalue = (3.262393874794,1.10187953003328)
RadiusRegion = 0.01
NumberEigenvalue = 1

Periode_Torsade = 3.0

CoordOtherFields = Cartesian
