# fichier de maillage
FileMesh = ./CableTiersBrins.mesh

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = B7F55 CIRCLE
# TypeCurve = B7F41 CIRCLE
TypeCurve = 4 CIRCLE

# ordre de discretisation
OrderDiscretization = 6

# Frequency = a b
# Frequence = a + b/(2*pi)  => pulsation = 2*pi*a + b
# Frequency = 2.0e-7 0.0
Frequency = 2.0e-4 0.0


# MateriauDielec = ref ISOTROPE epsilon 1/mu sigma
# pour sigma il faut multiplier par Z0 = sqrt(mu0/eps0) a cause de l'adimensionalisation
# materiau 1 => galvanized steel wire, eps = 1, sigma = 1.45e6, mu = 300
#MateriauDielec = 1 ISOTROPE 1.0  300.0  5.462e8
MateriauDielec = 1 ISOTROPE 1.0  300.0  5.462e5

# materiau 3 => polyethylene, eps = 2.25, mu = 1.0, sigma = 0
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0

# materiau 4 => sea water, eps = 81, mu = 1.0, sigma = 5.0
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.88e0

# materiau 2 => copper
# MateriauDielec = 2 ISOTROPE 1.0 1.0 2.18e7
MateriauDielec = 2 ISOTROPE 1.0 1.0 2.18e7

# bords Dirichlet
ReferenceDirichlet = 1
ReferencePeriodic = 5 6
NumberModePeriodic = 1
ReferenceConductor = 4 2
#ReferenceIsolant = 3

# ShiftEigenvalue
ShiftEigenvalue = (2.0, 0.2)
# ShiftEigenvalue = (0.0,0.0)
NumberEigenvalue = 30

# sortie sur une grille 2-D
SismoPlane = 0 0.2 -0.2 0.2 201 201

# sortie sur une courbe
SismoLine = 0.0 20.0 0.0 0.0 100000
SismoCircle = 0.0 0.0 0.108 1000
SismoCircle = 0.0 0.0 0.118 1000
SismoCircle = 0.0 0.0 1.108 1000
SismoCircle = 0.0 0.0 5.108 1000
SismoCircle = 0.0 0.0 10.108 1000


Eigensolver = Direct
#Eigensolver = Linear

CoordOtherFields = Cartesian

OnlyEz = NO

# valeurs/vecteurs propres du laplacien
LaplaceEigenvalue = NO
