  # frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
# frequence adimensionnelle = 60 Hz / 3e8 = 2e-7
Frequency = 2e-4 0.0

# fichier de maillage
FileMesh = DemiDisqueThreeLayer.mesh

# courbes presentes
TypeCurve = 1 CIRCLE
#TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE
TypeCurve = 5 CIRCLE
#TypeCurve = 6 CIRCLE

ReferenceDirichlet = 5

MateriauDielec = 2 ISOTROPE 1.0 1.0 21800000 6.0
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0 6.0
MateriauDielec = 1 ISOTROPE 1.0 300.0 546200.0 6.0
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.88e-0 6.0

# order of space approximation
OrderDiscretization = 4

# snapshots on a 2-D regular grid 200x200
SismoPlane = -0.2 0.2 -0.2 0.2 201 201
#SismoPlane = AUTO 200 200
SismoLine = 0.0 20.0 0.0 0.0 100001

OnlyEz = NO
ShiftEigenvalue = (3.29,1.18)
#ShiftEigenvalue = (5.0,2.0)
Eigensolver = Nleigs Split
#Eigensolver = Polynomial
#Eigensolver = Linear_Slepc
#Eigensolver = Direct
NumberEigenvalue = 5

Periode_Torsade = 6.0

CoordOtherFields = Cartesian
