# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
# frequence adimensionnelle = 60 Hz / 3e8 = 2e-7
Frequency = 0.01 0.0
#Frequency = 1.0 0.0

# fichier de maillage
FileMesh = DemiDisqueThreeLayer.mesh

# courbes presentes
TypeCurve = 1 CIRCLE
#TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE
TypeCurve = 5 CIRCLE
#TypeCurve = 6 CIRCLE

ReferenceDirichlet = 5

MateriauDielec = 2 ISOTROPE 2.0 3.0 10000.0
MateriauDielec = 3 ISOTROPE 1.0 1.0 0.0
MateriauDielec = 1 ISOTROPE 1.0 1.0 100000.0
MateriauDielec = 4 ISOTROPE 1.0 1.0 10.0

# order of space approximation
OrderDiscretization = 4

# snapshots on a 2-D regular grid 200x200
SismoPlane = -0.2 0.2 -0.2 0.2 201 201
SismoLine = 0.0 20.0 0.0 0.0 10001

OnlyEz = NO
ShiftEigenvalue = (2.0,1.6)
#ShiftEigenvalue = (5.0,2.0)
Eigensolver = Nleigs Split
#Eigensolver = Polynomial
#Eigensolver = Linear_Slepc
#Eigensolver = Direct
NumberEigenvalue = 10

Periode_Torsade = Inf

CoordOtherFields = Cartesian
