# fichier de maillage
FileMesh = Cercle.mesh

Ray = 0.2

TypeCurve = 1 CIRCLE

# ordre de discretisation
OrderDiscretization = 8

# il semblerait que la fréquence de coupure soit entre 0.5343 et 0.5344
Frequency = 10.0 0.0

# MateriauDielec = ref ISOTROPE rho
MateriauDielec = 1 ISOTROPE 10.0 1.0 0.0

# bords Dirichlet
ReferenceBord = 1
Condition = Dirichlet Linear

ShiftEigenvalue = (2.014,0.0)
Intervalle = 0 10 -0.5 0.5

NumberEigenvalue = 1

# sorties
SismoPlane = -0.2 0.2 -0.2 0.2 501 501
SismoLine = 0.0 0.2 0.0 0.0 10000
