# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
# frequence adimensionnelle = 60 Hz / 3e8 = 2e-7
Frequency = 2.0e-7 0.0

# fichier de maillage
FileMesh = Cable.mesh

# courbes presentes
TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE
TypeCurve = 5 CIRCLE
TypeCurve = 6 CIRCLE

ReferenceDirichlet = 1

# MateriauDielec = ref ISOTROPE epsilon 1/mu sigma
# pour sigma il faut multiplier par Z0 = sqrt(mu0/eps0) a cause de l'adimensionalisation
# materiau 1 => galvanized steel wire, eps = 1, sigma = 1.45e6, mu = 300
MateriauDielec = 1 ISOTROPE 1.0  300.0  5.462e8 3.0

# materiau 3 => polyethylene, eps = 2.25, mu = 1.0, sigma = 0
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0 3.0

# materiau 4 => sea water, eps = 81, mu = 1.0, sigma = 5.0
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.88e3 Inf

# materiau 2, 5, 6 => copper
MateriauDielec = 2 ISOTROPE 1.0 1.0 2.18e10 3.0
MateriauDielec = 5 ISOTROPE 1.0 1.0 2.18e10 3.0
MateriauDielec = 6 ISOTROPE 1.0 1.0 2.18e10 3.0

# references des cercles ici (pour le calcul de phi)
ReferenceConductor = 5 6 6 2 4 5
ReferenceIsolant = 3

# order of space approximation
OrderDiscretization = 6

# snapshots on a 2-D regular grid 200x200
SismoPlane = -0.2 0.2 -0.2 0.2 201 201
SismoLine = 0.0 20.0 0.0 0.0 100001

OnlyEz = NO
ShiftEigenvalue = (2.0,0.2)
#ShiftEigenvalue = (5.2,2.0)
Eigensolver = Nleigs Split
#Eigensolver = Linear_Slepc
#Eigensolver = Direct
NumberEigenvalue = 2

Periode_Torsade = 1.0

CoordOtherFields = Cartesian
