# fichier de maillage
FileMesh = ./Cable.mesh

Ray = 20.0

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE
TypeCurve = 5 CIRCLE
TypeCurve = 6 CIRCLE

# ordre de discretisation
OrderDiscretization = 4

# Frequency = a b
# Frequence = a + b/(2*pi)  => pulsation = 2*pi*a + b
Frequency = 2.0e-4 0.0


# MateriauDielec = ref ISOTROPE epsilon 1/mu sigma
# pour sigma il faut multiplier par Z0 = sqrt(mu0/eps0) a cause de l'adimensionalisation
# materiau 1 => galvanized steel wire, eps = 1, sigma = 1.45e6, mu = 300
MateriauDielec = 1 ISOTROPE 1.0  300.0  5.462e5

# materiau 3 => polyethylene, eps = 2.25, mu = 1.0, sigma = 0
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0

# materiau 4 => sea water, eps = 81, mu = 1.0, sigma = 5.0
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.88e0

# materiau 2, 5, 6 => copper
MateriauDielec = 2 ISOTROPE 1.0 1.0 2.18e7
MateriauDielec = 5 ISOTROPE 1.0 1.0 2.18e7
MateriauDielec = 6 ISOTROPE 1.0 1.0 2.18e7

# bords Dirichlet
#ReferenceDirichlet = 1

ReferenceConductor = 5 6 6 2 4 5
ReferenceIsolant = 3

# ShiftEigenvalue
ShiftEigenvalue = (2.0,0.2)
# ShiftEigenvalue = (0.0,0.0)
NumberEigenvalue = 2

# sortie sur une grille 2-D
SismoPlane = -0.2 0.2 -0.2 0.2 201 201

# sortie sur une courbe
SismoLine = 0.0 20.0 0.0 0.0 100000

Condition = Dirichlet Linear

Eigensolver = Nleigs Split
#Eigensolver = Nleigs Split

CoordOtherFields = Cartesian

OnlyEz = NO

Periode_Torsade = 3.0

# valeurs/vecteurs propres du laplacien
LaplaceEigenvalue = NO
