# fichier de maillage
FileMesh = CableTiersOne.mesh

TypeCurve = 1 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE
TypeCurve = 5 CIRCLE

# ordre de discretisation
OrderDiscretization = 4

# Frequency = a b
# Frequence = a + b/(2*pi)  => pulsation = 2*pi*a + b
Frequency = 2.0e-4 0.0


# blindage
MateriauDielec = 1 ISOTROPE 1.0 300.0 5.462e5
# cuivre
MateriauDielec = 2 ISOTROPE 1.0 1.0 2.18e7
# isolant (ligne facultative : valeurs par défaut)
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0
# eau
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.883

# bords Dirichlet
ReferenceDirichlet = 1
ReferencePeriodic = 5 6
NumberModePeriodic = 0
ReferenceConductor = 4 2
ReferenceIsolant = 3

# ShiftEigenvalue
ShiftEigenvalue = (2.2,0.7)
# ShiftEigenvalue = (0.0,0.0)

# sortie sur une grille 2-D
SismoPlane = 0 0.2 -0.2 0.2 201 201

# sortie sur une courbe
SismoLine = 0 10.0 0 0 10000

# valeurs/vecteurs propres du laplacien
LaplaceEigenvalue = NO
OnlyEz = YES
Eigensolver = Linear

CoordOtherFields = Cartesian
