# fichier de maillage
FileMesh = DemiDisqueOne.mesh

TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE

# ordre de discretisation
OrderDiscretization = 4

# Frequency = a b
# Frequence = a + b/(2*pi)  => pulsation = 2*pi*a + b
Frequency = 0.1 0.0

# MateriauDielec = ref ISOTROPE epsilon mu sigma
MateriauDielec = 2 ISOTROPE 2.0 3.0 1000.0
MateriauDielec = 1 ISOTROPE 1.0 1.0 0.0

# bords Dirichlet
ReferenceDirichlet = 3

#Eigensolver = Linear Slepc
Eigensolver = Nleigs Split
Condition = Dirichlet Non_Linear
#Eigensolver = Polynomial

ShiftEigenvalue = (1.58,1.09)
NumberEigenvalue = 1

Periode_Torsade = 10.0

# sorties
SismoPlane = AUTO 100 100
SismoLine = 0.0 0.2 0.0 0.0 10000
