# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
# frequence adimensionnelle = 60 Hz / 3e8 = 2e-7
Frequency = 2e-4 0.0

# fichier de maillage
FileMesh = DemiDisqueThreeLayers2.mesh
//FileMesh = DemiDisqueThreeLayer.mesh

Ray = 2.0


# courbes presentes
TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 5 CIRCLE

ReferenceDirichlet = 5

MateriauDielec = 2 ISOTROPE 1.0 1.0 21800000
MateriauDielec = 3 ISOTROPE 2.25 1.0 0.0
MateriauDielec = 1 ISOTROPE 1.0 300.0 546200.0
MateriauDielec = 4 ISOTROPE 81.0 1.0 1.88e-0

# bords
#ReferenceBord = 5

#Eigensolver = Nleigs Split
Condition = Dirichlet Non_Linear
#Condition = Neumann Linear
#Condition = BGT1 Non_Linear
#Condition = BGT2 Non_Linear
#Condition = BGT2 Linear 5

# order of space approximation
OrderDiscretization = 6

# snapshots on a 2-D regular grid 200x200
SismoPlane = -0.22 0.22 -0.22 0.22 201 201
#SismoPlane = AUTO 200 200
SismoLine = 0.0 2.0 0.0 0.0 10001

OnlyEz = NO
ShiftEigenvalue = (3.26,1.1)
NumberEigenvalue = 1

Periode_Torsade = 6.0

CoordOtherFields = Cartesian
