# fichier de maillage
FileMesh = DemiDisqueThreeLayers04.mesh

Ray = 0.4

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 5 CIRCLE

# ordre de discretisation
OrderDiscretization = 4

Frequency = 2e-4 0.0

# MateriauDielec = ref ISOTROPE rho
MateriauDielec = 2 ISOTROPE 1.0 1.735e10
MateriauDielec = 3 ISOTROPE 2.25
MateriauDielec = 1 ISOTROPE 300.0 1.304e11
MateriauDielec = 4 ISOTROPE 81.0 1.496e3

# bords
ReferenceBord = 5

Condition = Neumann
#Condition = BGT2 Linear 3
#Condition = BGT2 Non_Linear

#Eigensolver = Linear
#Eigensolver = Nleigs Split
ShiftEigenvalue = (3.29,1.18)
#Intervalle = 0.1 3.475 0.0 2.128
Intervalle = 0.1 10.0 0.0 1000.0

NumberEigenvalue = 10

# Orthogonalization = [mCoefMax] [ref sur laquelle on intègre (si rien : D Omega)]
# Ici j'orthogonalise sur l'intérieur du câble
Orthogonalization = 3 3

# sorties
#SismoPlane = AUTO 100 100
#SismoLine = 0.0 0.2 0.0 0.0 10000

SismoPlane = -0.4 0.4 -0.4 0.4 401 401
SismoLine = 0.0 0.4 0.0 0.0 10001
