# fichier de maillage
FileMesh = DemiDisqueOne04.mesh

Ray = 0.4

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE

# ordre de discretisation
OrderDiscretization = 1

# Frequency = a b
# Frequence = a + b/(2*pi)  => pulsation = 2*pi*a + b
Frequency = 10.0 0.0

# MateriauDielec = ref ISOTROPE epsilon mu sigma
MateriauDielec = 1 ISOTROPE 10.0
MateriauDielec = 2 ISOTROPE 1.0

# bords Dirichlet
ReferenceDirichlet = 2


Condition = BGT2 Linear 3

# sorties
#SismoPlane = AUTO 200 200
SismoPlane = -0.2 0.2 -0.2 0.2 401 401
SismoLine = 0.0 20.0 0.0 0.0 100000
