# fichier de maillage
FileMesh = DemiDisqueOneCrown06.mesh

Ray = 0.6

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE

# ordre de discretisation
OrderDiscretization = 8

Frequency = 2.0 0.0

# MateriauDielec = ref ISOTROPE rho
MateriauDielec = 3 ISOTROPE 2.0 0.5
MateriauDielec = 2 ISOTROPE 5.0 1000.0
MateriauDielec = 1 ISOTROPE 10.0

# bords Dirichlet
ReferenceBord = 3

#Condition = Neumann
Condition = BGT2 Linear 3
#Condition = BGT2 Non_Linear

#Eigensolver = Linear
#Eigensolver = Nleigs Split
ShiftEigenvalue = (2.57705876907829, 16.9239021619669)
Intervalle = 0.01 5.0 0.0 20.0
#Intervalle = 0.1 10.0 0.0 10.0

NumberEigenvalue = 2

# Orthogonalization = [mCoefMax] [ref sur laquelle on intègre (si rien : D Omega)]
# Ici j'orthogonalise sur l'intérieur du câble
Orthogonalization = 10 1

# sorties
#SismoPlane = AUTO 100 100
#SismoLine = 0.0 0.2 0.0 0.0 10000

SismoPlane = -0.6 0.6 -0.6 0.6 399 399
SismoLine = 0.0 0.6 0.0 0.0 10001
