# fichier de maillage
FileMesh = DemiDisqueThreeLayers04.mesh

Ray = 0.4

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 5 CIRCLE

# ordre de discretisation
OrderDiscretization = 8

Frequency = 10.0 0.0

# MateriauDielec = ref ISOTROPE rho
MateriauDielec = 2 ISOTROPE 10.0 1.0
MateriauDielec = 3 ISOTROPE 3.0 0.0
MateriauDielec = 1 ISOTROPE 100.0 2.0
MateriauDielec = 4 ISOTROPE 2.0 1.0

# bords Dirichlet
ReferenceBord = 5

#Condition = Neumann
Condition = BGT2 Linear 3
#Condition = BGT2 Non_Linear

#Eigensolver = Linear
#Eigensolver = Nleigs Split
ShiftEigenvalue = (1.12089780605352,0.62225598774394)
Intervalle = 0.1 3.475 0.0 2.128
#Intervalle = 0.1 10.0 0.0 10.0

NumberEigenvalue = 100

# Orthogonalization = [mCoefMax] [ref sur laquelle on intègre (si rien : D Omega)]
# Ici j'orthogonalise sur l'intérieur du câble
#Orthogonalization = 10 1

# sorties
#SismoPlane = AUTO 100 100
#SismoLine = 0.0 0.2 0.0 0.0 10000

SismoPlane = -0.4 0.4 -0.4 0.4 399 399
SismoLine = 0.0 0.4 0.0 0.0 10001
