# fichier de maillage
FileMesh = DemiDisqueOne021.mesh

Ray = 0.21

TypeCurve = 1 CIRCLE
TypeCurve = 2 CIRCLE

# ordre de discretisation
OrderDiscretization = 8

# il semblerait que la fréquence de coupure soit entre 0.5343 et 0.5344
Frequency = 10.0 0.0

# MateriauDielec = ref ISOTROPE rho
MateriauDielec = 2 ISOTROPE 1.0
MateriauDielec = 1 ISOTROPE 10.0

# bords Dirichlet
ReferenceBord = 2

Condition = BGT2 Linear 4
#Condition = BGT1 Non_Linear

#Eigensolver = Linear
#Eigensolver = Nleigs Split
ShiftEigenvalue = (3,0.0)
Intervalle = 0 10 -0.5 0.5

NumberEigenvalue = 12

#Orthogonalization = 3

# sorties
#SismoPlane = AUTO 100 100
#SismoLine = 0.0 0.2 0.0 0.0 10000

#SismoPlane = -2.0 2.0 -2.0 2.0 1001 1001
#SismoPlane = -1 1 -1 1 501 501
SismoPlane = -0.4 0.4 -0.4 0.4 501 501
#SismoPlane = -0.015 0.015 -0.015 0.015 501 501
SismoLine = 0.0 0.4 0.0 0.0 10001
