Frequency = 1.0

SourceCenter = 0
InitialCondition = Soliton
#InitialCondition = Gaussian

Formulation = Fdtd

#Model = Original
Model = Strong
#Model = Gentle
#Bottom = Flat
Bottom = Sinus

ComputationalDomain = -10 10 128
Order = 7

DisplayGrid = -10 10 AUTO 100

TimeOrder = 2 LeapFrog
#TimeOrder = 2 CrankNicolson
#TimeOrder = 2 Predictor
#TimeOrder = 4 RungeKutta
TimeStep = 0.0001

FinalTime = 15.0

FileOutputGrid = VnDiffExplicit.dat

Mu = 0.1
Epsilon = 0.1 0.0
Alpha = 0.1 0.0
Beta = 0.1 0.0

DataNonRegressionTest = camassa.x 0 1
