# adimensionalization of equations
Adimensionalization = YES

# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# incident angles (for incident field) theta and phi
IncidentAngle 90.0 0.0

# PhysicalFrequency = f (in Hz)
PhysicalFrequency = 1e7

# FileMesh = file_name
FileMesh = boite_cylinder.mesh

# TypeMesh = HEXA to enforce an hexahedral mesh
TypeMesh = HEXA

# to enforce a cylinder
TypeCurve = 1 CYLINDER 0 0 0 0 0 1.0 0.2

# order of space approximation 
OrderDiscretization = 2

# absorbing boundary condition for faces of reference 3
ConditionReference = 3 ABSORBING
# Dirichlet -> perfectly conducting boundary
ConditionReference = 1 DIRICHLET

# MateriauDielec = 1 ISOTROPE epsilon mu sigma
# since adimensionalization is required, sigma is given in S/m
MateriauDielec = 1 ISOTROPE 1 1 1e-4

# inhomogeneous Dirichlet condition
TypeSource = SRC_SURFACE 1 UNIFORM Polarization 0.0 0.0 100.0

# source oriented along e_z
Polarization = 0.0 0 1.0

# using a direct solver
#TypeSolver = DIRECT

# Gmres with Helmholtz preconditioning
TypeResolution = GMRES HELMHOLTZ_SSOR 0.5

# NumberMaxIterations = nb_iter_max restart
NumberMaxIterations = 1000 10

# stopping criterion for Gmres algorithm
Tolerance = 1e-7

# iterative matrix is not stored
ExplicitMatrixFEM = NO

# damping parameter used in preconditioning
DampingParameters = (0.7,0.4) 1.0

# non-linear solver used to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# File where coefficients Q_i are stored
FileCoefficientsQ = Coef.dat

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 0.0 0.0 0.0 AUTO 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracCubeCylinder totalCubeCylinder_F01_Max

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E only
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = maxwell3D.x 0 1
