# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 90.0 0.0

# cylinder
FileMesh = EXTRUDE 1 0.0 1.0 ring.mesh 2 \
           5 0 2 3 4 5 6 0 0 0 0 \
           1 1

# purely hexahedral mesh
TypeMesh = HEXA

# order of space approximation 
OrderDiscretization = 4

# boundary conditions
ConditionReference = 2 ABSORBING
ConditionReference = 3 DIRICHLET
ConditionReference = 4 5 CYCLIC
ConditionReference = 1 6 PERIODIC_Z

# MateriauDielec = ref ISOTROPE epsilon mu sigma
MateriauDielec = 1 ISOTROPE 1 1 0

# necessary for cyclic condition
UseSameDofsForPeriodicCondition = NO

# number of modes along z
NbModesPeriodic = 1 1 8

# scattering of a gaussian beam
TypeSource = SRC_TOTAL_FIELD GAUSSIAN_BEAM Waist 2.0

# polarization along e_y
Polarization = 0.0 1.0 0 

# using a direct solver
TypeSolver = DIRECT

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoGrille = 0.012 0.012 0.012 -5 5 -5 5 -4 4 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracCylinder totalCylinder

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E and H (proportional to curl E)
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell3D.x 0 1
