# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angles teta and phi of the incident plane wave 
# \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# these angles are in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0

# FileMesh = EXTRUDE nb_layers z0 z1 ... zn maillage_section nb_mailles_z  nb_surf ref1 ... ref2n  nb_vol ref1 ... refn
FileMesh = EXTRUDE 1   -1.0 1.0  hybrid_disque.mesh 6   3 2 0 3 4 0 0   1 1

# order of space approximation 
OrderDiscretization = 3

# hybrid mesh -> extrusion of triangles give prisms, and extrusion of quadrangles give hexas
TypeMesh = HYBRID

# curves
TypeCurve = 2 CYLINDER 0 0 0 0 0 1.0 1.0
TypeCurve = 3 CYLINDER 0 0 0 0 0 1.0 2.0


# boundary conditions
ConditionReference = 2 3 DIRICHLET
ConditionReference = 4 ABSORBING
ConditionReference = 1 ABSORBING

# epsilon and mu
MateriauDielec = 1 ISOTROPE 1 1

# TypeSource = SRC_SURFACE ref CIRCULAR_MODE AUTO voltage
# AUTO works only if there are TypeCurve with CYLINDER
# CIRCULAR_MODE means that the section is assumed to be circular crown
# the mode is then analytically known
TypeSource = SRC_SURFACE 1 CIRCULAR_MODE AUTO 1.0

# for a general surface, use SRC_MODE instead:
#TypeSource = SRC_MODE 1 POISSON 2  2 0.0 3 1.0  1.0

# direct solver
TypeSolver = DIRECT

# non-linear solver to invert Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 1e-10 1e-10 -0.999999999 AUTO 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracPoissonMax totalPoissonMax

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E and curl
ElectricOrMagnetic = -1

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell3D.x 0 8
