# type of finite element
TypeElement = HEXAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0

# n is the number of layers, file_mesh is the 2-D mesh to be extruded
# p0, p1 ... p_{n-1} are the number of subdivisions in each layer
# FileMesh = EXTRUDE n z0 z1 ... zn file_mesh p0 p1 ... p_{n-1} nb_ref_surf ref1 ref2 ref3 .. ref_p nb_ref_vol ref1 ref2 ... ref_m
FileMesh = EXTRUDE 5 0.0 1.0 4.0 5.0 6.0 10.0 DisqueCoaxialTronque.mesh 4 8 3 3 10    \
           5  5 0 12 4 12   0 0 0 0 0    5 0 12 4 12   7 7 10 0 0    5 11 12 4 0   9 9 0 0 0 \
              5 11 12 4 0  8 8 10 0 0    5 0 12 4 12   6 6 6 0 0    3   1 2 2   1 2 2  1 2 0  1 2 0  1 2 2

# order of space approximation 
OrderDiscretization = 3

# hybrid mesh
TypeMesh = HYBRID

# curved elements
TypeCurve = 4 CYLINDER 0 0 0 0 0 1.0 0.1
TypeCurve = 5 CYLINDER 0 0 0 0 0 1.0 0.16
TypeCurve = 12 CYLINDER 0 0 0 0 0 1.0 0.2

# debut du cable
ConditionReference = 1 2 3 DIRICHLET
# surface laterale exterieure
ConditionReference = 10 11 12 DIRICHLET
# surface laterale interieure
ConditionReference = 4 DIRICHLET
# bout du cable
ConditionReference = 6 ABSORBING

# epsilon mu and sigma
MateriauDielec = 1 ISOTROPE 1 1
MateriauDielec = 2 ISOTROPE 1 1 0.5
MateriauDielec = 3 ISOTROPE 1 1 0.5

# TypeSource = SRC_MODE ref1 ref2 ... refn POISSON nb_pot NORMAL ref1 val1 ref2 val2
TypeSource = SRC_MODE 1 2 3 POISSON 2 4 0.0 12 1.0  1.0

# dipole oriented along e_y
Polarization = 0.0 1.0 0

# iterative solver with ILUT preconditioning
TypeResolution = COCG ILUT 1e-10 ILUT 100000 1e-4 0.01 1.0 

# damping parameters used in the preconditioning
DampingParameters = (1,1) 1

# NumberMaxIterations = nb_iter_max restart
NumberMaxIterations = 100000 10

# stopping criterion
Tolerance = 1e-8

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 5e-16 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 0.0 0.0 5.0 AUTO 200 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracCylinderCoaxialTronque totalCylinderCoaxialTronque

#ParametersOutputPlane = 0.0 10.0 0.1
#SismoPlane = -0.2 -0.2 4.0  0.2 -0.2 4.0  -0.2 0.2 4.0  200 200
#SismoPlane = -0.2 -0.2 5.0  0.2 -0.2 5.0  -0.2 0.2 5.0  200 200
#SismoPlane = -0.2 -0.2 6.0  0.2 -0.2 6.0  -0.2 0.2 6.0  200 200
#FileOutputPlane = diffracPlane totalCubePlaneEllipse

# iterative matrix is not stored
ExplicitMatrixFEM = NO

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E only
ElectricOrMagnetic = -2

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = maxwell3D.x 0 1

