# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 100.0 0.0

# incident angles teta and phi of the incident plane wave 
# \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0.0

# FileMesh = BALL r0 r1 nb_points_per_unit ref_intern_surface REGULAR
FileMesh = BALL 1 1.5 1 1 REGULAR

# if HEXA, only hexahedral elements are used to mesh the ball
TypeMesh = HEXA

# order of space approximation 
OrderDiscretization = 5

# curved element
TypeCurve = 1 SPHERE
TypeCurve = 3 SPHERE

# boundary conditions for faces of reference 3
ConditionReference = 3 ABSORBING

# MateriauDielec = 1 ISOTROPE rho mu sigma
MateriauDielec = 1 ISOTROPE 0.002 0.05 0.0
MateriauDielec = 2 ISOTROPE 0.002 0.05 0.0

# Dirac source delta
TypeSource = SRC_DIRAC

# polarization of source
Polarization = 1.0 0.0 0.0

# source point for Dirac source
OriginePhase = 0.15 0.1 0.2

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to invert Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 100x100x100
SismoGrille = 0 0 0 -1.5 1.5 -1.5 1.5 -1.5 1.5 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTest totalDirac3D_Max

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the component Ex of E
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 3

DataNonRegressionTest = maxwell3D.x 0 8
