# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 90.0 0.0

# polarization of the source (Ex Ey Ez)
Polarization = 0 1 0

# file where the mesh is stored
FileMesh = fente3D_all_tet.mesh REFINED 2

# order of space approximation 
OrderDiscretization = 3

# boundary condition for faces of reference 1, 2 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 2 3 ABSORBING

# scattering problem with gaussian beam of waist 2
#TypeSource = SRC_DIFFRACTED_FIELD GAUSSIAN_BEAM Waist 2.0
TypeSource = SRC_TOTAL_FIELD GAUSSIAN_BEAM Waist 2.0

# direct solver
TypeSolver = DIRECT

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 200x200x200 (only three planes, not all the volume)
SismoGrille = 1e-10 1e-10 1e-10 AUTO 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracFente3D_Max totalFente3D_Max

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E and curl
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell3D.x 0 8
