# type of finite element
TypeElement = HEXAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angles teta and phi of the incident plane wave 
# \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0.0

# FileMesh = SPHERE a b nb_points r0 r1
# creation of a mesh inside two spheres of radius a and b
# nb_points is number of points by unity
# r0 r1 are internal spheres
FileMesh = SPHERE 0.8 1.5 4.0 1.1 1.3

# TypeMesh = HEXA to produce a mesh with hexahedrals only
TypeMesh = HEXA

# order of space approximation 
OrderDiscretization = 5

# curved boundaries
TypeCurve = 1 SPHERE
TypeCurve = 3 SPHERE
TypeCurve = 4 SPHERE
TypeCurve = 5 SPHERE

# impedance condition : n/mu x rot E = Z (n x E) x n
# the impedance Z with the following line :
# ConditionReference = 1 IMPEDANCE Z
ConditionReference = 1 IMPEDANCE 2.0

# Silver-Muller condition
ConditionReference = 3 ABSORBING

# to define a body (for transparent condition)
TypeBody = 5 1

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# MateriauDielec = ref ISOTROPE epsilon mu sigma
MateriauDielec = 1 ISOTROPE 1 1
MateriauDielec = 2 ISOTROPE 2 3.0
MateriauDielec = 3 ISOTROPE 0.6 1.5

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 100x100x100
SismoGrille = 0 0 0 -1.5 1.5 -1.5 1.5 -1.5 1.5 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracImpedanceMulti totalImpedanceMulti

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# put YES if you want a transparent condition
# "YES r" means that you want an order of integration (on the intern boundary) of r
# YES AUTO means that the order of integration is equal to order of approximation
TransparencyCondition = YES 1 AUTO
# GMRES nb_iter_max stopping_criterion restart
ParamResolutionTransparency = GMRES 100 1e-8 10

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 3

DataNonRegressionTest = maxwell3D.x 0 8
