# type of finite element
TypeElement = HEXAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 0.5 0.0

# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0.0

# polarization of the source (Ex Ey Ez)
Polarization = 1 0 0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = BALL 1 1.5 1 1 REGULAR

# purely hexahedral mesh
TypeMesh = HEXA

# order of space approximation 
OrderDiscretization = 5

# curved element
TypeCurve = 1 SPHERE
TypeCurve = 3 SPHERE

# boundary conditions for faces of reference 3
ConditionReference = 3 ABSORBING

# dielectric properties (epsilon and mu)
MateriauDielec = 1 ISOTROPE 1.0 1.0
MateriauDielec = 2 ISOTROPE (2,1.0) (1.5,0.25)

# diffracted field of a plane wave exp(ikx)
#TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE
TypeSource = SRC_TOTAL_FIELD PLANE_WAVE

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 100x100x100 (on three planes only)
SismoGrille = 0 0 0 AUTO 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracSphereDieMax totalSphereDieMax

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
# only surfacic mesh (referenced triangles and quadrangles)
SismoMeshSurfacic = AUTO REFERENCE 1
# files where the snapshots on subdivided mesh are stored
FileOutputMeshSurfacic = diffrac_surfDielecMax.bb total_surfDielecMax.bb

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E and curl
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 3

DataNonRegressionTest = maxwell3D.x 0 8
