# type of finite element
TypeElement = HEXAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angles teta and phi of the incident plane wave \vec{k} = (k sin teta cos phi, k sin teta sin phi, k cos teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 180.0 0.0

# FileMesh = SPHERE a b nb_points
# creation of a mesh inside two spheres of radius a and b
# nb_points is number of points by unity
FileMesh = SPHERE 1.0 1.5 2

# purely hexahedral mesh
TypeMesh = HEXA

# order of space approximation 
OrderDiscretization = 4

# curved element
TypeCurve = 1 SPHERE
TypeCurve = 3 SPHERE

# boundary conditions for faces of reference 1 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 3 ABSORBING

# to define a body (for transparent condition)
TypeBody = 1 1

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# polarization of the plane wave
Polarization = 1.0 0 0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 100x100x100 (on three planes)
SismoGrille = 0 0 0 -1.5 1.5 -1.5 1.5 -1.5 1.5 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracCondMax totalCondMax

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
SismoMeshVolumetric = AUTO
# files where the snapshots on subdivided mesh are stored
FileOutputMeshVolumetric = diffrac_volCondMax.bb total_volCondMax.bb

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
# only surfacic mesh (referenced triangles and quadrangles)
SismoMeshSurfacic = AUTO REFERENCE 3
# files where the snapshots on subdivided mesh are stored
FileOutputMeshSurfacic = diffrac_surfCondMax.bb total_surfCondMax.bb

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E and curl
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# put YES if you want a transparent condition
# "YES r" means that you want an order of integration (on the intern boundary) of r
# YES AUTO means that the order of integration is equal to order of approximation
TransparencyCondition = YES 1 AUTO
# GMRES nb_iter_max stopping_criterion restart
ParamResolutionTransparency = GMRES 100 1e-4 10

# Parameters for RCS
# YES or NO if you want or not that a radar cross section is computed
# reference of the boundary condition where the rcs must be computed (this reference is used for the definition of transparent condition)
# order of integration used (AUTO to select same order than discretization)
ParametersRCS = YES 1 AUTO
# first angle, final angle and number of angles between
AngleRCS = -90.0 270.0 361
FileRCS = Rcs_SphereMax.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 3

DataNonRegressionTest = maxwell3D.x 0 8
