# type of finite element
TypeElement = TETRAHEDRON_FIRST_FAMILY

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# file where the mesh is stored
FileMesh = guide3D.mesh

# order of approximation
OrderDiscretization = 5

# MateriauDielec = 1 ISOTROPE SQUARE refractive_index mu
MateriauDielec = 1 ISOTROPE SQUARE 1.44 1.0
MateriauDielec = 2 ISOTROPE SQUARE 3.48 1.0

# boundary conditions
ConditionReference = 3 5 ABSORBING
#ConditionReference = 4 DIRICHLET
ConditionReference = 4 ABSORBING

# TypeSource = SRC_MODE ref MAXWELL shift nb_eigen_to_compute nb_eigen_to_combine \
#                               num1 coef1 num2 coef2 ... num_n coef_n 
TypeSource = SRC_MODE 4 MAXWELL 1.570796 10  1 9 1.0 

# PML layers are added to the domain
# AUTO means that number of layers is computed according to the space step
AddPML = YES PML_X+YZ 0.5 1
DampingPML = 1.2

# using a direct solver
TypeSolver = DIRECT
#TypeResolution = COCG IDENTITY

# non-linear solver used to invert Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 3-D regular grid 100x100x100 (on three planes)
SismoGrille = 0.0 0 0 AUTO 100 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputGrille = diffracTaper totalTaper

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution E and curl
ElectricOrMagnetic = -2

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell3D.x 0 1





