# type of finite element
TypeElement = TRIANGLE_CLASSICAL

# type of equation
TypeEquation = HARMONIC_GALBRUN_MODEL_DIV

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0 0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = disque_tri.mesh

# order of space approximation 
OrderDiscretization = 8

# Penalization coefficients
PenalizationDG = -1.0 -1.0

# refinement around a vertex artificially added
AddVertex = 2.0 2.0
RefinementVertex = 2.0 2.0 3 2.0

# non-zero entries below this value are dropped
ThresholdMatrix = 1e-30

# Neumann boundary condition
TypeCurve = 3 CIRCLE
ConditionReference = 3 NEUMANN

# variable physical coefficients
MateriauDielec = 1 ISOTROPE SAME_MESH DATA/disque.mesh 0 0.02 DATA/MxLee_Circle.don 10 1.0 \
                            SAME_MESH DATA/disque.mesh 0 0.02 DATA/MyLee_Circle.don 10 1.0 \
                            0.5 \
                            SAME_MESH DATA/disque.mesh 0.0 1.0 DATA/RhoLee_Circle.don 10 1.0 \
                            SAME_MESH DATA/disque.mesh 0.0 1.0 DATA/C0Lee_Circle.don 10 1.0 \
                            SAME_MESH DATA/disque.mesh 0.0 1.0 DATA/P0Lee_Circle.don 10 1.0

# Dirac source on point (0.5, 0.5)
#TypeSource = SRC_DIRAC
#OriginePhase = 2.0 2.0
TypeSource = SRC_VOLUME GAUSSIAN 2.0 2.0  0.2

# source in u_x
Polarization = 0.0 0.0 1.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve Fi(X) = Y
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 400 400
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracTestGhost totalAeroDisqueGalbrun

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = galbrun.x 0 8
