TypeElement = TRIANGLE_CLASSICAL
TypeEquation = HARMONIC_GALBRUN_SIPG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  ref_media  ref1 ref2 ref3 ref4
# nb_x : number of subdivisions along x
# ref_media reference of the elements (quadrilaterals or triangles)
# ref1, ref2, ref3, ref4 references of the edges y = ymin, x = xmax, y = ymax and x = xmin
FileMesh = REGULAR 25 -4.0  4.0  -4.0  4.0  1  1  2  3  4

# order of space approximation
OrderDiscretization = 8

PenalizationDG = -10.0 -10.0

# boundary condition for edges of reference 3
ConditionReference = 1 3 PERIODICITY
ConditionReference = 2 4 PERIODICITY

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 1.0

Polarization = 1 0

# MateriauDielec = 1 ISOTROPE u0 v0 sigma rho0 c0 p0
MateriauDielec = 1 ISOTROPE RANDOM -4.0 4.0 -4.0 4.0 0 0 0 1.0 example/galbrun/flowSinus.don DOUBLE  0.2 \
                            0.0 0.1 1.0 1.0 1.0

TypeSolver = AUTO

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputPlane = 0.0 10.0 1.0
# snapshots on all the mesh
SismoPlane = AUTO 200 200
# diffracted and total field (in this test case, we compute only total field)
FileOutputPlane = diffracTestGhost.dat totalHarmonicGalbrunSipg.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the solution U (not the gradient)
ElectricOrMagnetic = -2

StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = galbrun.x 0 8
