# type of finite element
TypeElement = QUADRANGLE_HCURL_AXI

# type of equation
TypeEquation = HARMONIC_MAXWELL

# path where the meshes are stored
MeshPath = MAILLAGES/

# PhysicalFrequency = frequency in Hz
PhysicalFrequency = 2.92e9

# IndicentAngle = theta phi of the indicent plane wave
# wave vector k = (k sin teta cos phi, k sin teta sin phi, k cos teta)
IncidentAngle = 180.0 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DemiDisquePML.mesh)
FileMesh = diedre_disque_pml.mesh

# order of space approximation 
OrderDiscretization = 5

# curved element
TypeCurve = 2 CIRCLE

# YES for a mixed formulation with both E and H
MixedFormulation = YES
#ModifiedFormulation = YES

# NumberModes = N for a manual selection of the number of modes
NumberModes = AUTO 1e-12

# PML are added for y < ymin and y > ymax
# and x > xmax (since we consider half-plane region in axisymmetric computation)
AddPML = YES PML_X+Y 0.1 AUTO
DampingPML = 4.0

# boundary conditions
ConditionReference = 1 2 DIRICHLET
ConditionReference = 3 ABSORBING

# On the axis, a fictitious Neumann boundary condition is set
ConditionReference = 4 NEUMANN

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# polarization E0 of the plane wave
Polarization = 1.0 0 0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# we want to know the solution U only
ElectricOrMagnetic = -2

# a body is defined for the rcs
TypeBody = 1 1
TypeBody = 2 1

# rcs will be computed on body 1
# monostatic rcs induce multiple right hand sides
ParametersRCS = YES 1 AUTO MONOSTATIC

# first angle, final angle and number of angles between
AngleRCS = 0.0 180.0 181

# FileRCS = rcs far_field
# the far_field will contain the values of (Ex, Ey, Ez) (real and imaginary part)
FileRCS = Rcs_ConeSphereAxi.dat FarFieldConeSphereAxi.dat

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = maxwell_axi.x 0 8
