# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = src/Program/Unit/Instationary/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 0.98 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  ref_media  ref1 ref2 ref3 ref4
# nb_x : number of subdivisions along x
# ref_media reference of the elements (quadrilaterals or triangles)
# ref1, ref2, ref3, ref4 references of the edges y = ymin, x = xmax, y = ymax and x = xmin
FileMesh = disque.mesh

# order of space approximation 
OrderDiscretization = 1

TypeCurve = 1 CIRCLE
TypeCurve = 3 CIRCLE

# boundary condition for edges of reference 3
ConditionReference = 3 ABSORBING

# rho mu and sigma
MateriauDielec = 1 ISOTROPE 1.8 2.2 0.05
MateriauDielec = 2 ISOTROPE 2.5 1.4 0.02

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 2.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve
NonLinearSolver = MINPACK 1e-15 50

# snapshots on a 2-D regular grid 200x200
#SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
#FileOutputPlane = diffracCarre totalCarre

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

TimeStep = 0.05

TimeInterval = -0.2 60.0
TemporalSource = RICKER

OrderTimeScheme = 4 LEAP_FROG_PML

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

ExplicitMatrixFEM = NO
#SplitDomain = Scotch

# put YES if you want to store the matrix on the disk
StorageMatrix = NO AhRef.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = helmholtz2D.x 0 8
