# finite element used
TypeElement = QUADRANGLE_LOBATTO

# solved equation
TypeEquation = ACOUSTIC_HDG

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 8.0 0.0

# incident angle
IncidentAngle = 0.0

# file where the mesh is stored in the folder specified by MeshPath
FileMesh = DisqueResonant.mesh

# order of space approximation
OrderDiscretization = 1

# boundary conditions
ConditionReference = 1 ABSORBING
ConditionReference = 2 4 5 NEUMANN

# RefinementVertex = x0 y0 level ratio
RefinementVertex = -4.999238475781956e-01  8.726203218641719e-03  2 4.0
RefinementVertex = -4.999238475781956e-01  -8.726203218641719e-03  2 4.0
RefinementVertex = -9.999619259638773e-01  8.726203218641719e-03 2 4.0
RefinementVertex = -9.999619259638773e-01  -8.726203218641719e-03 2 4.0

# TypeCurve = ref CIRCLE
TypeCurve = 1 2 3 4 CIRCLE

# MateriauDielec = 1 ISOTROPE rho mu sigma
MateriauDielec = 1 ISOTROPE 0.8 1.2 0.0
MateriauDielec = 2 ISOTROPE 1.0 1.0 0.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6

# plane wave : TypeSource = SRC_TOTAL_FIELD AUTO
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 0.15

# solver used
TypeSolver = DIRECT
#StaticCondensation = YES Store

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want the solution U only
ElectricOrMagnetic = 0

# time step deltat
TimeStep = 0.01

# initial time of the experience, final time
TimeInterval = 0.0 10.1

# theta scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
OrderTimeScheme = 8 PADE_SCHEME Stable

# temporal dependance of the source
# TemporalSource = RICKER
TemporalSource = SINUS_GAUSSIAN 4.0

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = acous2D.x 10 8
