#TypeOutput = Medit ASCII
TypeOutput = Matlab BINARY

# SismoGrille  = x0 y0 z0 xmin xmax ymin ymax zmin zmax nx ny nz
SismoGrille = 0.0 0.0 0.0 -1.5 1.5 -1.5 1.5 -1.5 1.5 100 100 100

# TotalField = YES
TotalField = YES

# if no, -i/omega curl E is computed
ElectricField = NO

# TypeCondition = DIRICHLET, NEUMANN or IMPEDANCE beta
# for IMPEDANCE, the condition is n/mu \times curl E = beta E_tangential
# this condition is set on the first radius
TypeCondition = IMPEDANCE 2.0

# Epsilon = eps0 eps1 ... eps_n
Epsilon = 2.0 0.6 1.0

# Mu = mu0 mu1 ... mu_n
Mu = 3.0 1.5 1.0

# if YES, a Silver-Muller condition is set at the last radius
FirstOrder_ABC = NO

# NEAR_FIELD, FAR_FIELD or SURFACIC_FIELD
TypeData = NEAR_FIELD

# NumberModes = AUTO for an automatic computation
NumberModes = 28

# RadiusSphere = r0 r1 r2 r_final
# the solution is computed when r0 <= r <= r_final
# the intermediaries radii r1, r2 are associated with the interface between materials
RadiusSphere = 0.8 1.1 1.3 1.5

# Frequency = f
Frequency = 1.0

# for output with Medit
# MeshFile = file_name 
MeshFile = sphere.mesh

# OutputFile = FileEx FileEy FileEz
OutputFile = ExSolExacte.dat EySolExacte.dat EzSolExacte.dat

# for non-regression informations
TypeElement = ANALYTIC
TypeEquation = HARMONIC_MAXWELL
DataNonRegressionTest = solution.x 0 1
