#TypeOutput = Medit ASCII
TypeOutput = Matlab BINARY

# SismoGrille  = x0 y0 z0 xmin xmax ymin ymax zmin zmax nx ny nz
SismoGrille = 0.0 0.0 0.0 -2.0 2.0 -2.0 2.0 -2.0 2.0 100 100 100

# if NO, the diffracted field is computed
TotalField = NO

# if no, -i/omega curl E is computed
ElectricField = YES

# Perfectly conducting boundary condition E x n = 0
TypeCondition = DIRICHLET

# if YES, a Silver-Muller condition is set at the last radius
FirstOrder_ABC = NO

# NEAR_FIELD, FAR_FIELD or SURFACIC_FIELD
TypeData = NEAR_FIELD

# RadiusSphere = r0 .. r_{n+1}
RadiusSphere = 1.0 2.5

# Frequency = freq
Frequency = 1.0

# output files for Ex, Ey, Ez
OutputFile = ExDirichletRef.dat EyDirichletRef.dat EzDirichletRef.dat

# Parameters for the radar cross section
AngleRCS = 0 180 181
FileRCS = Rcs_Sphere.dat

# NumberModes = n (n : number of Bessel functions)
# NumberModes = AUTO for an automatic computation
NumberModes = AUTO

# for non-regression informations
TypeElement = ANALYTIC
TypeEquation = HARMONIC_MAXWELL
DataNonRegressionTest = solution.x 0 1
