# TypeOutput = Matlab BINARY  or Medit ASCII
TypeOutput = Matlab BINARY

# SismoGrille  = x0 y0 z0 xmin xmax ymin ymax zmin zmax nx ny nz
SismoGrille = 0.0 0.0 0.0 -2.0 2.0 -2.0 2.0 -2.0 2.0 100 100 100

# total field or diffracted field
TotalField = YES

# computation of electric field E, or -i/omega curl E
ElectricField = YES

# Epsilon = eps0 eps1 .. eps_n
Epsilon = (2,1.0) 1.0

# Mu = mu0 mu1 .. mu_n
Mu = (1.5,0.25) 1.0

# if YES, a Silver-Muller condition is set at the last radius
FirstOrder_ABC = NO

# NEAR_FIELD, FAR_FIELD or SURFACIC_FIELD
TypeData = NEAR_FIELD

# if r0 = 0, a dielectric ball is present for r <= r1
# otherwise a condition is set on r = r0
# RadiusSphere = r0 r1 r2 .. r_{n+1}
RadiusSphere = 0.0 1.0 2.5

# Frequency = freq
Frequency = 0.5

# output files for Ex, Ey, Ew
OutputFile = ExDielectricRef.dat EyDielectricRef.dat EzDielectricRef.dat

# number of Bessel functions
# AUTO  computes automatically the number of Bessel functions needed to reach the machine precision
NumberModes = 20

# for non-regression informations
TypeElement = ANALYTIC
TypeEquation = HARMONIC_MAXWELL
DataNonRegressionTest = solution.x 0 1
