#TypeOutput = Medit ASCII
TypeOutput = Matlab BINARY

# SismoGrille  = x0 y0 z0 xmin xmax ymin ymax zmin zmax nx ny nz
SismoGrille = 0.0 0.0 0.0 -2.0 2.0 -2.0 2.0 -2.0 2.0 100 100 100

# if NO, the diffracted field is computed
TotalField = NO

#  if NO, -i/omega curl E is computed
ElectricField = YES

# if YES, a Silver-Muller condition is set at the last radius
FirstOrder_ABC = NO

# Epsilon and Mu should be set to 1 on the last layer (vacuum)
Epsilon = 3.0 2.0 1.0
Mu = 1.5 2.0 1.0

# NEAR_FIELD, FAR_FIELD or SURFACIC_FIELD
TypeData = NEAR_FIELD

# RadiusSphere = r0 r1 r2 r_final
# the solution is computed when r0 <= r <= r_final
# the intermediaries radii r1, r2 are associated with the interface between materials
RadiusSphere = 0.0 0.8 1.25 2.5

# Frequency = freq
Frequency = 0.5

# output files for Ex, Ey and Ez
OutputFile = ExMultiLayerRef.dat EyMultiLayerRef.dat EzMultiLayerRef.dat

# parameters for RCS
AngleRCS = 0 180 181
FileRCS = Rcs_Sphere.dat

# number of spherical Bessel functions
# AUTO for a machine precision computation
NumberModes = AUTO

# for non-regression informations
TypeElement = ANALYTIC
TypeEquation = HARMONIC_MAXWELL
DataNonRegressionTest = solution.x 0 1
