#!/usr/bin/env python

import os, string, sys

if (len(sys.argv) != 4):
  print("Entrez trois arguments surf_Ex_ 1 100")
  sys.exit(0)

racine = sys.argv[1]
debut = int(sys.argv[2])
fin = int(sys.argv[3])

for i in range(debut,(fin+1)):
  if (i < 10):
    entier = "000" + str(i)
  elif (i < 100):
    entier = "00" + str(i)
  elif (i < 1000):
    entier = "0"+str(i)
  elif (i < 10000):
    entier = str(i)
  else:
    print("too many snapshots");
    sys.exit(0);
  
  fichier_ppm = racine +'.'+ str(i) + ".ppm"
  fichier_jpg = racine +'.'+ entier + ".jpeg"
  if (os.access(fichier_jpg, os.F_OK)):
    os.remove(fichier_jpg)
  
  commande = "convert -quality 90 "+ fichier_ppm +" "+fichier_jpg
  os.system(commande)
