#!/usr/bin/env python

import os, string, sys

if (len(sys.argv) != 4):
  print("Entrez trois arguments totalLung 1 100")
  sys.exit(0)

racine = sys.argv[1]
debut = int(sys.argv[2])
fin = int(sys.argv[3])
fichier_mesh = sys.argv[1] + ".mesh"

for i in range(debut,(fin+1)):
  link_mesh = racine + '.' + str(i) + ".mesh"
  commande = "ln -s " + fichier_mesh + " " + link_mesh
  os.system(commande)
