TypeElement = EDGE_LOBATTO

# boundary conditions on the left and right side of the interval
#BoundaryCondition = IMPEDANCE 2.5 ABC
BoundaryCondition = NEUMANN ABC

# order of approximation
OrderDiscretization = 10

# MateriauDielec = ref rho mu sigma
MateriauDielec = 1 SPLINE example/helm_radial/rho.don SPLINE example/helm_radial/mu.don SPLINE example/helm_radial/sigma.don
#MateriauDielec = 1  1.0 1.0  0.0

# in order to have laplacian in spherical coordinates
CoordinatesLaplacian = SPHERICAL

# FileMesh = REGULAR n xmin xmax
FileMesh = example/helm_radial/radius_geom.don

# TypeSource = SRC_GAUSSIAN x0 y0 z0 r0
#TypeSource = SRC_GAUSSIAN 0 0 0.984788088381 0.01 1.0 0.015
TypeSource = SRC_GAUSSIAN 0 0 0.8 0.02 1.0 0.04
#TypeSource = SRC_GAUSSIAN 0 0 0.0 0.1 1.0 0.2
#TypeSource = SRC_DIRAC 0 0 0

RefinementVertex = 0.8 2 2.0

# Frequency = a b sets omega = 2*pi*a + b
Frequency = 2.1e6 0.0

# NumberModes = AUTO Lmax threshold
NumberModes = AUTO 760 1e-14

# SismoGrille = x0 y0 z0 AUTO nx ny nz
SismoGrille = 0 0 0 AUTO 200 200 200

# FileOutputGrille = file_diffrac file_total
FileOutputGrille = diffracHelioRadial totalHelioRadial

DataNonRegressionTest = helmholtz_radial.x 0 1
