TypeElement = EDGE_LOBATTO

# boundary conditions on the left and right side of the interval
BoundaryCondition = NEUMANN DIRICHLET

# order of approximation
OrderDiscretization = 10

# FileMesh = REGULAR n xmin xmax
# FileMesh = LAYERED x0 x1 ... xN AUTO dx
FileMesh = LAYERED 0 1.0 1.03 AUTO 0.01

# MateriauDielec = ref rho mu sigma
# each index can be specified by :
# constant
# SPLINE file_name
# FILE file_name
MateriauDielec = 1 1.5625e-08 1.0 0.000390625
MateriauDielec = 2 FILE example/helm_radial/rho_exp.don FILE example/helm_radial/mu_exp.don FILE example/helm_radial/sigma_exp.don

# in order to have laplacian in spherical coordinates
CoordinatesLaplacian = SPHERICAL

# only mode 0 will be excited
TypeSource = SRC_GAUSSIAN_R 0 0 0.8 0.03 1.0 0.06

# Frequency = a b sets omega = 2*pi*a + b
Frequency = 4.0e5 0.0

# NumberModes = AUTO Lmax threshold
NumberModes = AUTO 0 1e-14

# output on a line
SismoLineAxi = 0 0 0 0 0.5 1.03 1000
FileOutputLineAxi = titi UnHelioExpoRadial.dat

PrintLevel = 2

OutputFormat = BINARY DOUBLE
ElectricOrMagnetic = 0

ScalingMatrix = YES

DataNonRegressionTest = helmholtz_radial.x 0 1
