TypeElement = EDGE_LOBATTO

# boundary conditions on the left and right side of the interval
BoundaryCondition = IMPEDANCE 2.5 ABC

# order of approximation
OrderDiscretization = 8

# MateriauDielec = ref rho mu sigma
MateriauDielec = 1  1.8 1.2  0.3
MateriauDielec = 2  2.0 0.75  0.1
MateriauDielec = 3  1.0 1.0  0.0

# in order to have laplacian in spherical coordinates
CoordinatesLaplacian = SPHERICAL

# FileMesh = REGULAR n xmin xmax
FileMesh = LAYERED 0.8 1.5 2.0 3.0 AUTO 0.25

TypeSource = SRC_DIFFRACTED_FIELD
IncidentAngle = 90 90

# Frequency = a b sets omega = 2*pi*a + b
Frequency = 1.0 0.0

# NumberModes = AUTO Lmax threshold
NumberModes = AUTO 60 1e-14

# SismoGrille = x0 y0 z0 AUTO nx ny nz
SismoGrille = 0 0 0 AUTO 200 200 200

# FileOutputGrille = file_diffrac file_total
FileOutputGrille = diffracSphereImpedanceRadial.dat totalSphereImpedanceRadial.dat

DataNonRegressionTest = helmholtz_radial.x 0 1
