TypeElement = EDGE_LOBATTO

# boundary conditions on the left and right side of the interval
BoundaryCondition = DIRICHLET ABC

# order of approximation
OrderDiscretization = 10

# MateriauDielec = ref rho mu sigma
MateriauDielec = 1  50.0 2.0  0.0

# in order to have laplacian in spherical coordinates
CoordinatesLaplacian = SPHERICAL

# FileMesh = REGULAR n xmin xmax
FileMesh = REGULAR 5 1.0 2.0

TypeSource = SRC_TOTAL_FIELD
IncidentAngle = 65 -38

# Frequency = a b sets omega = 2*pi*a + b
Frequency = 0.25 0.0

# NumberModes = AUTO Lmax threshold
NumberModes = AUTO 40 1e-14

# SismoGrille = x0 y0 z0 AUTO nx ny nz
SismoGrille = 0 0 0 -2 2 -2 2 -2 2 200 200 200

# FileOutputGrille = file_diffrac file_total
FileOutputGrille = diffracSphereRadialDirichlet totalSphereRadialDirichlet

DataNonRegressionTest = helmholtz_radial.x 0 1
