# type of finite element
TypeElement = TRIANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.000732 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file where the mesh is stored (path is added -> MAILLAGES/AtmelH09.mesh)
FileMesh = AtmelH09.mesh

TypeMesh = TRI

# boundary conditions
ConditionReference = 2 NEUMANN
ConditionReference = 3 ABSORBING

# curves
TypeCurve = 4 CIRCLE 6547.860255099433  0.0  6548.756451612903
TypeCurve = 5 CIRCLE 6548.256451612903  0.0   6548.756451612903
TypeCurve = 6 CIRCLE -6548.256451612903  0.0   6548.756451612903
TypeCurve = 7 CIRCLE -6547.860255099433  0.0   6548.756451612903

# dielectric indices
MateriauDielec = 2 ISOTROPE 9.954025 1.0

# order of space approximation 
OrderDiscretization = 6

# scattering by a gaussian beam
TypeSource = SRC_TOTAL_FIELD GAUSSIAN_BEAM Waist 6.4

# PML layers are added along x, and for y > ymax
AddPML = YES PML_X_Y+ 1.0 AUTO
# damping factor for PML
DampingPML = 2.0

# automatic resolution of the linear system
TypeSolver = AUTO

NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = -4 4 0.01 20 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracAtmel totalAtmel

# solution at output of the device
SismoLine = 3.5 3.5 0 20  200
FileOutputLine = diffracOutput totalOutput

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# level of display
PrintLevel = 2

DataNonRegressionTest = helmholtz2D.x 0 8
