# type of finite element
TypeElement = TRIANGLE_LOBATTO

# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 2.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 60.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = burger_defaut.mesh

TypeMesh = QUAD

# order of space approximation 
OrderDiscretization = 8

# curved element
TypeCurve = 2 CIRCLE
TypeCurve = 3 CIRCLE
TypeCurve = 4 CIRCLE
TypeCurve = 5 CIRCLE

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 2 3 DIRICHLET
ConditionReference = 5 NEUMANN

MateriauDielec = 1 ISOTROPE 2.0 1.2 0.0
MateriauDielec = 2 ISOTROPE 1.5 2.5 0.0
MateriauDielec = 3 ISOTROPE 3.0 4.0 0.0

# if (rho0, mu0) are different from (1, 1), you specify the reference of the infinity
ReferenceInfinity = 1

# PML layers are added to the domain
# AUTO means that number of layers is computed according to the space step
#AddPML = YES PML_X thickness AUTO
AddPML = YES PML_X 0.5 2
# radial PML can be added after x-pml or y-pml :
# AddPML = ref PML_R thickness nb_cells
AddPML = 2 PML_R 0.5 2
AddPML = 3 PML_R 0.5 2

# damping factor for PML
DampingPML = 3.0

# scattering by a plane wave in a layered media
# LAYERED_PLANE_WAVE nb_intern_layers z0 rho0 mu0 z1 rho1 mu1 ... zn
TypeSource = SRC_DIFFRACTED_FIELD LAYERED_PLANE_WAVE 1  2.0 1.2 -0.5 1.5 2.5   0.5

# automatic solver
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 100x100
SismoPlane = -3.0 3.0 -3.0 3.0 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = DiffracBurger.dat TotalBurger.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 4

DataNonRegressionTest = ./helmholtz2D.x 0 8
