# type of finite element
TypeElement = TRIANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 60.0

# file where the mesh is stored (path is added -> MAILLAGES/cockpit.mesh)
FileMesh = cockpit_tri.msh

# order of space approximation 
OrderDiscretization = 3

# dielectrical material
MateriauDielec = 1 ISOTROPE (1,0.1) (1,-0.02)
MateriauDielec = 3 ISOTROPE 2.5 1.2
MateriauDielec = 4 ISOTROPE 1 1

# boundary conditions
ConditionReference = 1 DIRICHLET
ConditionReference = 3 ABSORBING

# definition of body for transparent condition
TypeBody = 2 1

# diffracted field of a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# direct resolution with Pastix
TypeSolver = DIRECT

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracCockpit totalCockpit

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# put YES if you want a transparent condition
# "YES r" means that you want an order of integration (on the intern boundary) of r
# YES AUTO means that the order of integration is equal to order of approximation
TransparencyCondition = YES 1 AUTO 4
# GMRES nb_iter_max stopping_criterion restart
ParamResolutionTransparency = GMRES 100 1e-4 10

# Parameters for RCS
# YES or NO if you want or not that a radar cross section is computed
# reference of the boundary condition where the rcs must be computed (this reference is used for the definition of transparent condition)
# order of integration used (AUTO to select same order than discretization)
ParametersRCS = YES 1 AUTO BISTATIC 4

# first angle, final angle and number of angles between
AngleRCS = 0.0 360.0 361
FileRCS = Rcs_Cockpit.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 3

DataNonRegressionTest = helmholtz2D.x 0 8
