# type of finite element
TypeElement = TRIANGLE_LOBATTO

# type of equation
TypeEquation = HELMHOLTZ

# path where the meshes are stored
MeshPath = MAILLAGES/

# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 2.0 0.0

# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
#FileMesh = disquePML.mesh
FileMesh = DisqueCond_QUAD.mesh

TypeMesh = QUAD

# order of space approximation 
OrderDiscretization = 6

# curved element
TypeCurve = 1 CIRCLE
TypeCurve = 3 CIRCLE

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 DIRICHLET
ConditionReference = 3 ABSORBING

# PML layers are added to the domain
# AUTO means that number of layers is computed according to the space step
#AddPML = YES PML_XY 1.0 AUTO
AddPML = YES PML_R 0.5 AUTO

# damping factor for PML
DampingPML = 4.0

# scattering by a plane wave exp(ikx)
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# automatic solver
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 100x100
SismoPlane = AUTO 200 200
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracCirclePML totalCirclePML

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 4

DataNonRegressionTest = ./helmholtz2D.x 0 8
