# type of finite element
TypeElement = TRIANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file where the mesh is stored (path is added -> MAILLAGES/DisqueCond_QUAD.mesh)
FileMesh = disquePML.mesh REFINED 2

# order of space approximation 
OrderDiscretization = 4

# curved element
TypeCurve = 1 CIRCLE

# boundary condition for edges of reference 1 and 3
ConditionReference = 1 NEUMANN
ConditionReference = 3 ABSORBING

# PML layers are added to the domain
# AUTO means that number of layers is computed according to the space step
AddPML = YES PML_XY 1.0 AUTO

# damping factor for PML
DampingPML = 2.0

# scattering by a plane wave exp(ikx)
TypeSource = SRC_TOTAL_FIELD PLANE_WAVE

# iterative solved preconditioned with a multigrid iteration
# parameters of the multigrid algorithm are selected automatically
#TypeSolver = MULTIGRID
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 100x100
SismoPlane = -1.99999999 1.999999999 -1.999999999 1.999999999 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracNeu totalNeu

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 4

DataNonRegressionTest = helmholtz2D.x 0 8
