# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ_HDG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.48 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax  ref_media  ref1 ref2 ref3 ref4
# nb_x : number of subdivisions along x
# ref_media reference of the elements (quadrilaterals or triangles)
# ref1, ref2, ref3, ref4 references of the edges y = ymin, x = xmax, y = ymax and x = xmin
FileMesh = fenetre.mesh

# order of space approximation 
OrderDiscretization = 8

PenalizationDG = Upwind

RefinementVertex = -4.0 -1.0 1 2.0
RefinementVertex = -2.0 -1.0 1 2.0
RefinementVertex = 2.0 -1.0 1 2.0
RefinementVertex = 4.0 -1.0 1 2.0

# boundary condition for edges of reference 3
ConditionReference = 1 5 DIRICHLET
ConditionReference = 2 6 NEUMANN
ConditionReference = 3 7 IMPEDANCE 2.5
ConditionReference = 4 8 ABSORBING

ConditionReference = 9 ABSORBING

StaticCondensation = YES Store

# inhomogeneous condition on four surfaces
TypeSource = SRC_SURFACE 1 VARIABLE DATA/PointsFenetre1.txt DATA/ValueFenetre1.dat
TypeSource = SRC_SURFACE 2 VARIABLE DATA/PointsFenetre2.txt DATA/ValueFenetre2.dat
TypeSource = SRC_SURFACE 3 VARIABLE DATA/PointsFenetre3.txt DATA/ValueFenetre3.dat
TypeSource = SRC_SURFACE 4 VARIABLE DATA/PointsFenetre4.txt DATA/ValueFenetre4.dat

AddPML = YES PML_XY 1.0 AUTO
DampingPML = 2.0

MateriauDielec = 1 ISOTROPE 0.6 1.4 0.0

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to solve
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 300 300
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracFenetre totalFenetre

SismoLine = -4.0 -2.0 -1.0 -1.0  200
SismoLine = 2.0 4.0 -1.0 -1.0  200
SismoLine = -1.0 1.0 2.0 2.0  200
SismoLine = -1.0 1.0 -1.0 -1.0  200
FileOutputLine = diffracLineFenetre totalLineFenetre


# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -2

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat.dat

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz2D.x 0 8
