# type of finite element
TypeElement = QUADRANGLE_DG_GAUSS
# type of equation
TypeEquation = HELMHOLTZ_DG
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# file where the mesh is stored (path is added -> MAILLAGES/AtmelH09.mesh)
FileMesh = fente.mesh

TypeMesh = QUAD
MixedFormulation = YES

# boundary conditions
ConditionReference = 3 ABSORBING
ConditionReference = 1 NEUMANN

# order of space approximation 
OrderDiscretization = 6

# scattering by a gaussian beam
TypeSource = SRC_DIFFRACTED_FIELD GAUSSIAN_BEAM Waist 3.2

# PML layers are added along x, and y
AddPML = YES PML_XY 1.0 AUTO

DampingPML = 2.0

# automatic resolution of the linear system
TypeSolver = AUTO

NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 100 201
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracFente totalFente

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = 0

# level of display
PrintLevel = 3

DataNonRegressionTest = helmholtz2D.x 0 8
