# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency and/or pulsation
# Frequency = a b
# sets the pulsation omega = 2*pi*a + b
Frequency = 1.51 0.0
# incident angle teta of the incident plane wave \vec{k} = (k cos teta, k sin teta)
# this angle is in degrees (0, 90, 180 by example)
IncidentAngle = 0.0

# mesh
FileMesh = fenteT.mesh

TypeMesh = QUAD

# order of space approximation 
OrderDiscretization = 4

# boundary conditions (Neumann for lateral boundaries, absorbing at right, dirichlet at left)
ConditionReference = 2 NEUMANN
ConditionReference = 3 ABSORBING
ConditionReference = 1 DIRICHLET

# SRC_MODE ref MODE shift nb_modes_computed nb_modes_combined n0 ampl0 n1 ampl1 lateral_boundary_condition
# ref is the reference mesh where the mode should be imposed
TypeSource = SRC_MODE 2 MODE 0.0 2 1 0 1.0 DIRICHLET

# automatic resolution of the linear system (selection of the optimal algorithm)
TypeSolver = AUTO

# non-linear solver to invert transformation Fi
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 200x200
SismoPlane = AUTO 100 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracFenteT totalFenteT

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U only
ElectricOrMagnetic = 0

# put YES if you want to store the matrix on the disk
StorageMatrix = NO mat_

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 2

DataNonRegressionTest = helmholtz2D.x 0 4
