# type of finite element
TypeElement = QUADRANGLE_LOBATTO
# type of equation
TypeEquation = HELMHOLTZ
# directory where the meshes are read
MeshPath = ./
# Frequency = a b
# will mean that omega = 2*pi*a + b
Frequency = 1.0 0.0
# incident angle
IncidentAngle = 0

# file where the mesh is
# For a regular mesh, the syntax is
# FileMesh = REGULAR  nb_subdiv_x  xmin  xmax  ymin  ymax   ref_domain  ref1 ref2 ref3 ref4
# ref_domain is the reference of the domain (put 1)
# ref1, ref2, ref3 and ref4 are references of the four edges of the rectangle
FileMesh = REGULAR 101 0.0 40.0 -10.0 10.0  1 1 3 1 3

# order of space approximation 
OrderDiscretization = 4

# boundary conditions
ConditionReference = 3 ABSORBING
ConditionReference = 1 NEUMANN
IrregularMesh = NO

# RANDOM xmin xmax ymin ymax troncX troncY offset amplitude file rho_infty
#MateriauDielec = 1 ISOTROPE 1.0 1.0
MateriauDielec = 1 ISOTROPE RANDOM 10.0 30.0 -10 10 1.0 1.0  1  2.0 example/helm2D/rand.don FLOAT 1.0   \
                             1.0

# scattering by a plane wave
#TypeSource = SRC_TOTAL_FIELD PLANE_WAVE
TypeSource = SRC_DIFFRACTED_FIELD PLANE_WAVE

# To have more informations, increase this number (0 essential informations)
PrintLevel = 2

# Put YES to add PML layers, PML_X to add the PML along x, 
AddPML = YES PML_X 1.0 AUTO

# Damping factor
DampingPML = 2.0

# automatic resolution of linear system
TypeSolver = AUTO

# non-linear solver to solve F_i (X) = Y 
NonLinearSolver = NEWTON 1e-15 50

# snapshots on a 2-D regular grid 100x100
SismoPlane = AUTO 200 100
# files where the diffracted and total field will be stored (extension .dat is added)
FileOutputPlane = diffracRandom totalRandom

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
OutputFormat = BINARY DOUBLE

# we want to know the solution U and gradients
ElectricOrMagnetic = -1

DataNonRegressionTest = helmholtz2D.x 0 8







