TypeElement = HEXAHEDRON_DG_GAUSS
TypeEquation = AERO_ACOUSTIC
# path where the meshes are stored
MeshPath = MAILLAGES/
# frequency of the temporal source
# Frequency = a b means that the pulsation omega = 2*pi*a + b 
Frequency = 1.0 0.0

# for a regular mesh, put FileMesh = REGULAR nb_x xmin xmax ymin ymax zmin zmax  ref_media  ref1 ref2 ref3 ref4 ref5 ref6
# nb_x : number of subdivisions along x
# ref_media reference of the elements (hexahedrals or tetrahedrals)
# ref1, ref2, ref3, ref4, ref5, ref6 references of the faces x = xmin, y = ymin, z = zmin, z = zmas, y = ymax and x = xmax
#FileMesh = REGULAR 7 -3.0  3.0  -3.0  3.0  -3.0 3.0   1  3  3  3  3  3  3 
FileMesh = rec_sphere.mesh
#FileMesh = SPHERE_CUBE 1.0 3.0 2

# order of space approximation
OrderDiscretization = 5

TypeCurve = 1 SPHERE

# with penalization, more stability ...
PenalizationDG = -0.5 -0.5

# boundary conditions
ConditionReference = 1 DIRICHLET
ConditionReference = 2 DIRICHLET
ConditionReference = 3 ABSORBING

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 z0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN -2.0 0.0 0.0 1.0

# source is on p, v ? (p u_0 v_0 w_0)
Polarization = 1.0  0 0 0

# MateriauDielec = 1 ISOTROPE u0 v0 w0 sigma rho0 c0 p0
# each index u0, v0, w0, sigma, rho0, c0 or p0 can be specified 
# - as constant : 0.5 ,
# - as defined on a regular grid : RANDOM xmin xmax ymin ymax zmin zmax troncX troncY troncZ offset amplitude file
#   in this case, troncX, troncY and troncZ are coefficients in order to smooth the index 
#   so that it will be equal to 0 near the boundaries of the grid.
#   If you don't want to smooth the index, put 0
# - as defined on a mesh : MESH file_mesh offset amplitude file_data order
#   order is the order of approximation used to define the index on the mesh
MateriauDielec = 1 ISOTROPE MESH MAILLAGES/rec_sphere.mesh 0 0.5 example/aero3D/flowSphere.elb 5 0.5 \
                            0.0 0.0 0.0 1.0 1.0 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 20.0 1.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 200 200 200
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat aeroSphereGrid.dat

# tend tbegin deltat for seismogramms
ParametersOutputPoint = 0.0 40.0 0.02
# diffracted and total field (in this test case, we compute only total field)
FileOutputPoint = diffracPoint.dat totalPoint_AeroSphere.dat
# you can add as many points you want, all the results will be stored in the same file totalPoint.dat
SismoPoint = 2.5 0.0 0.0
SismoPoint = -2.5 0.0 0.0

# snapshots on a subdivided mesh (AUTO means that number of subdivisions will be equal to order of approximation)
# only surfacic mesh (referenced triangles and quadrangles)
#SismoMeshSurfacic = AUTO REFERENCE 1
# files where the snapshots on subdivided mesh are stored
#FileOutputMeshSurfacic = diffrac_surfAeroSphere.bb total_surfAeroSphere.bb
#ParametersOutputMeshSurfacic = 0.0 30.0 1.0

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

#NonLinearSolver = NEWTON 1e-14 50

# we want all the unknowns of the solution (p, v_x and v_y)
ElectricOrMagnetic = -2

# step time deltat
TimeStep = 0.008

# initial time of the experience, final time
TimeInterval = 0.0 5.0

# fourth order Runge-Kutta scheme
OrderTimeScheme = 4 RUNGE_KUTTA_LOW
#OrderTimeScheme = 50 TALEZER 150 100

# temporal dependance of the source
#TemporalSource = SINUS_GAUSSIAN 0.1
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = aero3D.x 4 8
