TypeElement = HEXAHEDRON_DG_GAUSS
TypeEquation = AERO_ACOUSTIC
# path where the meshes are stored
MeshPath = ./
Frequency = 1.0 0.0

FileMesh = REGULAR 6 -2.0  2.0  -2.0  2.0  -2.0 2.0  1  1  2  3  4  5  6

TypeMesh = HEXA

# order of space approximation
OrderDiscretization = 7

PenalizationDG = -0.5 -0.5

# neumann condition on lateral faces
# periodic condition between boundary x = xmin and x = xmax
ConditionReference = 2 3 4 5 DIRICHLET
ConditionReference = 1 6 PERIODICITY

# u0 v0 w0 sigma rho0 c0 p0
MateriauDielec = 1 ISOTROPE 0.5 0 0 0.0 1.0 1.0 1.0

# Gaussian source : TypeSource = SRC_VOLUME GAUSSIAN x0 y0 radius
# where (x0, y0) is the center of the gaussian, radius is so that f(radius) = 1e-6
TypeSource = SRC_VOLUME GAUSSIAN 0.0 0.0 0.0 1.0

# initial time, final time, and step time between each snapshot
# tend tbegin deltat
ParametersOutputGrille = 0.0 10.0 2.0
# snapshots on all the mesh
SismoGrille = 0 0 0 AUTO 200 200 200
# diffracted and total field (in this test case, we compute only total field)
FileOutputGrille = diffracTest.dat totalCubeAero.dat

# ASCII or BINARY (binary needs less memory), FLOAT or DOUBLE (simple or double precision)
# seismogramms are always on ascii format
OutputFormat = BINARY DOUBLE

# we want only the solution U (not the gradient)
ElectricOrMagnetic = 0

# steo time deltat
TimeStep = 0.02

# initial time of the experience, final time
TimeInterval = 0.0 10.0

# leap-frog scheme or order two, applied on equation of order 2 (d^2 u/dt^2 - Delta u = f )
#OrderTimeScheme = 2 LEAP_FROG_PML
#OrderTimeScheme = 200 TALEZER 150 300
OrderTimeScheme = 4 RUNGE_KUTTA_LOW

# temporal dependance of the source
TemporalSource = RICKER

# level of display (-1 for no display, 0 for minimal display, 10 for debug ...)
PrintLevel = 6

DataNonRegressionTest = aero3D.x 4 8
